### ISSUE TITLE
Investiguer l'erreur que SC Form rencontre sur les requêtes d'envoi à notre API - A embarquer 5 septembre

### ISSUE THREAD

**Issue by stephane-ruhlmann** [mission-apprentissage/flux-retour-cfas#1011]
https://reqbin.com/curl

```
curl --location --request POST 'https://cfas.apprentissage.beta.gouv.fr/api/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "",
    "password": ""
}'
```

- [ ] Investiguer l'erreur
- [ ] Corriger ou faire les cartes nécessaires
- [ ] Automatisation possible d'identification et de correction ? 
- [ ] Décision et cartes afférentes
- [ ] Coupler avec le point SC Form sur les rupturants / abandons : https://github.com/mission-apprentissage/flux-retour-cfas/issues/1651

**Comment by sbenfares** [comment]
Solution temporaire : contourner via appel axios avec l'option `insecureHTTPParser: true `
