### ISSUE TITLE
Mesurer l'utilisation du TdB par les agents des DREETS - juin /juillet - ???

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1324]
**Objectif : le TDB permet aux DREETS de piloter l’apprentissage**

_Mesurer l'utilisation du TdB par les agents des DREETS_

Faire un point pour définir le besoin exact avec @stephane-ruhlmann @MelanieRAPHAEL @pabloHry @sbenfares 

**Definition of done**

- [x] #1536
- [x] https://github.com/mission-apprentissage/flux-retour-cfas/issues/1537
- [x] #1540
- [x] #1541
- [ ] Mettre ces requêtes sur la page Metabase stats interne "Mesure d'impact" créé ici : https://github.com/mission-apprentissage/flux-retour-cfas/issues/1325

**Comment by Anne-Camille** [comment]
non reprise dans new kanban => tests utilisateurs  semaine du 17/10 + carte restitution des tests en bl + carte requête metabase fréquence des logs
