### ISSUE TITLE
Mettre en place Semantic Release

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#1562]
**Objectif**

_Décrire ici l'objectif de la carte_

https://www.npmjs.com/package/semantic-release

Alors il y a un webhook slack sur le pipeline publish
[11 h 33](https://mission-apprentissage.slack.com/archives/D03B098TJE6/p1658827997355229)
      - name: publish sdk
        run: |
          cd server
          yarn npm:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SDK }}

avec un plugin semantic-release-slack-bot

**Definition of done**

- [ ] _Cette étape est terminée_
- [ ] _Cette autre étape est terminée_

**Comment by stephane-ruhlmann** [comment]
Fait par Antoine ici : https://github.com/mission-apprentissage/flux-retour-cfas/pull/1869
