### ISSUE TITLE
Présenter à des CFA le prototype PS

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1574]
**Objectif**

_Afin de tester la solution sans ERP sur un territoire où une grande partie des CFA est dans cette situation, reprendre contact avec Fabrice Bouillot (au 27 juillet il avait répondu n'avoir trouvé aucun volontaire disponible pour les entretiens en cette période)_

**Definition of done**

- [ ] _Cette étape est terminée_
- [ ] _Cette autre étape est terminée_

**Comment by Anne-Camille** [comment]
non reprise new kanban => obsolète car  tests réalisés début octobre
