### ISSUE TITLE
Mémoire de Pablo - septembre

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1598]
**Objectif**

En vue du mémoire écrit de @pabloHry , à rendre pour le 14 octobre :

**Definition of done**
Pour fin septembre le mémoire est entièrement rédigé
Il a été relu par au moins un membre de l'équipe

- [x] Rédaction du plan détaillé => @pabloHry 
- [x] Transmission du plan à Samir => @pabloHry 
- [x] Relecture par ACM Julianne
- [x] Ajustements suite commentaires et rédaction => @pabloHry 
- [x] Présentation du mémoire / relecture complète par au moins 1 membre de l'équipe
- [x] Envoi du mémoire à l'OF => @pabloHry

**Comment by sbenfares** [comment]
Lien mémoire : https://docs.google.com/document/d/1s5DoIztsm01J0I7dGRH84jiBmfaXX6pRtFUNFuS-6Nc/edit?usp=sharing

**Comment by MelanieRAPHAEL** [comment]
@pabloHry tu en es ou ?
