### ISSUE TITLE
Réunion Pilotage données ERP - Fiabilisation et Pilotage interne / Début septembre

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1619]
**Objectif**

Rapport d'erreurs par Sofia : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=4759%3A102302

**Definition of done**

- [ ] Organiser un échange avec @stephane-ruhlmann @cathbaiona @MelanieRAPHAEL @RaphBeta @christophebonraisin 
- [ ] Définir les enjeux liés avec l'API V2
- [ ] Modéliser un tableau de pilotage (entre données de fiabilisation, rapport d'erreurs, etc / par ERP et avec historisation)
- [ ] Définir un calendrier et l'équipe opérationnelle

**Comment by Anne-Camille** [comment]
non repris new kanban => obsolète avec les travaux en cours
