### ISSUE TITLE
Mise en ligne nouvelle HomePage

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1675]
**Retours re7**

- [x] non bloquant pour la mep : décalage textes en dehors des card (Edge Version 106.0.1370.47)
<img width="881" alt="image" src="https://user-images.githubusercontent.com/63646363/196425876-5f5d69b7-566e-4911-be46-fcf42e9783ac.png">

- [x] non boquant pour la mep : faute d'orthographe, remplacer "reccueillir" par "recueillir"
<img width="254" alt="image" src="https://user-images.githubusercontent.com/63646363/196426146-25b1eade-40e2-4510-85ec-bfab0162b164.png">

- [x] non bloquant pour la mep : faute d'orthographe footer, remplacer "license" par "licence" (je sais ce n'est pas à proprement parler la home, mais je le glisse là :) ! )
<img width="123" alt="image" src="https://user-images.githubusercontent.com/63646363/196426388-48dffef5-d772-441e-9ed0-780cd9d97255.png">

- [ ] gênant mais non bloquant pour la mep : chiffres à la journée affichés comme des chiffres au mois => soit mettre les chiffres du début du mois jusqu'au jour de consultation, soit mettre en clair "chiffres du [date]".
<img width="902" alt="image" src="https://user-images.githubusercontent.com/63646363/196426938-16d6a3a0-0154-496c-b5e5-146d40c2c8f7.png">

- [x] bloquant pour la mep : wording à revoir sur une bonne partie des éléments (tournures de phrases, acronymes non expliqués, messages interprétables...), voir avec Julianne sur l'aspect communication stratégique. => voir ce doc pour les wording à remplacer + les parties à supprimer/modifier : https://docs.google.com/presentation/d/1_bjiwlag_Z5n4u6UYsdkVkmfL2DNaq6dCGs1G3u1X4o/edit?usp=sharing

**Objectif**

_Mettre en ligne la nouvelle HomePage avec le nouveau parcours pour mise en cohérence et pour pouvoir accéder à partage simplifié_

Maquette @cathbaiona @ClemLan : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=5056%3A119049

**Definition of done**

- [ ] _Le nouveau parcours HP est en ligne_

**Comment by cathbaiona** [comment]
- [ ] Mettre à jour les chiffres : 

<img width="1278" alt="Capture d’écran 2022-10-19 à 09 30 55" src="https://user-images.githubusercontent.com/108516993/196625450-1895f41f-e52d-4321-9037-9399

- [ ] A l'avenir, lorsque PS sera en ligne, possible de faire un lien cliquable ?

<img width="438" alt="Capture d’écran 2022-10-19 à 09 31 21" src="https://user-images.githubusercontent.com/108516993/196625547-a9337a08-2deb-46ea-926e-fc150d54891b.png">
5460b42c.png">

- [ ] Retirer pour l'instant ce lien, car PS n'est pas encore en Prod. A remettre dès qu'il le sera :-)

<img width="306" alt="Capture d’écran 2022-10-19 à 09 32 18" src="https://user-images.githubusercontent.com/108516993/196625742-107a1229-7804-4254-8485-46461ff8bd9b.png">

- [ ] Revoir le padding bas de chaque tuile

<img width="1269" alt="Capture d’écran 2022-10-19 à 09 32 56" src="https://user-images.githubusercontent.com/108516993/196625846-f273c895-7ede-4269-9d95-d4867af85601.png">

**Comment by pabloHry** [comment]
" A l'avenir, lorsque PS sera en ligne, possible de faire un lien cliquable ?" : Oui

**Comment by Anne-Camille** [comment]
@pabloHry sur le wording + blocs à supprimer, je t'ai mis un lien vers un doc dans la carte où tout est détaillé. Cela impacte certains retours de Catherine qui concernent des parties qu'il faut supprimer.
