### ISSUE TITLE
Revoir la page "Comprendre les données"

### ISSUE THREAD

**Issue by cathbaiona** [mission-apprentissage/flux-retour-cfas#1720]
**Objectif**

Revoir le texte de cette page https://cfas.apprentissage.beta.gouv.fr/comprendre-les-donnees afin de permettre une meilleure compréhension par les utilisateurs des données récoltées et pourquoi on le fait (donner du sens)

**Definition of done**

- [ ] Ecriture et relecture des textes
- [ ] Adaptation du design

**Comment by cathbaiona** [comment]
@ClemLan Si tu as du temps pour que je te la présente ?

**Comment by ClemLan** [comment]
@cathbaiona la semaine pro ? (lundi par ex)

**Comment by cathbaiona** [comment]
@MelanieRAPHAEL j'ai presque finalisé cette page aujourd'hui mais encore besoin d'un peu de temps au prochain sprint pour finaliser. J'aurai besoin de ta relecture.
