### ISSUE TITLE
Support - Traitement demande Gestibase N°1

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#1755]
**Traitement demande mail Gestibase - erreur données**

- [x] Ecrire à Gestibase pour les informer de la prise en compte de leur demande @RaphBeta 
- [x] investiguer le problème et évaluer le temps de travail pour redresser les données
- [ ] Faire un retour à Gestibase
- [ ] Redresser la données

Mail du 5-09-22 à 17h29
Bonjour,
Nous avons été contactés par la MFR de CRANVES-SALES (0741630V) qui nous indique ne pas retrouver le même nombre d'apprentis sur le tableau de bord de l'apprentissage par rapport à son iGesti.
Sur iGesti, ils ont 158 apprentis alors que sur le tableau de bord apprentissage il est indiqué 148 apprentis et 2 rupturants. 
Après vérification, dans notre envoi de ce matin (cf fichier joint), il y a bien 158 apprentis transférés de iGesti pour la MFR de CRANVES-SALES (0741630V).
Serait-il possible de nous expliquer l'écart entre les données envoyées et celles affichées sur le tableau de bord de l'apprentissage ?
D'avance merci de votre retour.
Cordialement,
Anne-Virginie.

@stephane-ruhlmann @pabloHry

**Comment by stephane-ruhlmann** [comment]
Pour consulter les données qui étaient utilisées le 5 septembre 2022 pour le calcul des effectifs, j'ai utilisé ces filtres :
* uai_etablissement : 0741630V
* created_at : avant le 6 septembre 2022
* annee_scolaire : 2022-2023 ou 2022-2022

Voilà la vue Metabase correspondant : https://cfas.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzQsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsODkzLG51bGxdLCIwNzQxNjMwViJdLFsiPSIsWyJmaWVsZCIsOTExLG51bGxdLCIyMDIyLTIwMjIiLCIyMDIyLTIwMjMiXSxbIjwiLFsiZmllbGQiLDg2NixudWxsXSwiMjAyMi0wOS0wNiJdXSwib3JkZXItYnkiOltbImRlc2MiLFsiZmllbGQiLDg2NixudWxsXV1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLmNvbHVtbl93aWR0aHMiOltudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsMTAyM119LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==

Il ressort bien 160 apprenants dont 158 avec un contrat d'apprentissage signé MAIS pour 10 d'entre eux, la date de valeur transmise (champ `date_metier_mise_a_jour_statut` est ultérieure au 05/09/2022 (idem pour la date de début de contrat, qui doit correspondre à la même valeur) : ces apprenants ne peuvent être donc considérés comme apprentis.

Si je consulte en date d'aujourdhui (23/10/2022), j'ai 173 apprentis et 2 rupturants.

**Comment by stephane-ruhlmann** [comment]
Réponse faite à Anne-Virginie
