### ISSUE TITLE
Traiter demande CNAM pour passage en PROD

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#1796]
Traiter demande CNAM pour passage en PROD (mail jeudi 6 octobre) :  

Bonjour,

Nous avons bien noté que le code CFD est une donnée obligatoire. De fait, en attendant l'intégration du code CFD au niveau du Cnam national, nous avons modifié notre outil pour permettre aux responsables des différents centres Cnam de saisir le code CFD de chaque formation concernée.
Ainsi nous pourrons déjà de vous faire des remontées sans avoir à attendre cette intégration. Le seul « bémol » est que la remontée sera potentiellement partielle, le temps que les informations soient bien renseignées dans notre logiciel, puisque nous ne remontrons pas les apprentis concernés par une formation si le code CFD de la formation est absent (pour ne pas remonter des données erronées).
Nous avons effectué un test d'envoi en masse (+ de 10000 dossiers pour 2021) sur votre environnement de développement https://cfas-dev.apprentissage.beta.gouv.fr/api/ sans rencontrer d'erreur. Avant que nous procédions au déploiement en production de la remontée, pouvez-vous nous confirmer que vous recevez bien les données et qu'elles sont conformes ? (hormis en ce qui concerne le code CFD, où nous avons indiqué un code de test 00000000 puisque nous n'avons pour l'heure pas la donnée).

Merci pour votre retour.
Cordialement,
Nicolas Muller
Chef de projet Gescicc@ - Lab'S DN

Le Cnam'IDS
Rue des Crayères – BP 1034 - 51687 Reims Cedex 2
Nouvelles coordonnées téléphoniques : 03 51 25 25 20

**Comment by stephane-ruhlmann** [comment]
Vue Metabase de la donnée créée : https://cfas-dev.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzMsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsOTQ0LG51bGxdLCJjbmFtIl0sWyI9IixbImZpZWxkIiw5MjgsbnVsbF0sIjIwMjItMTAtMDQiXV19LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUucGl2b3QiOmZhbHNlfSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=
