### ISSUE TITLE
Support - Traitement écart Gestibase N°2

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#1813]
**Traitement demande mail Gestibase - erreur données**

- [x] Ecrire à Gestibase pour les informer de la prise en compte de leur demande @RaphBeta 
- [x] investiguer le problème et évaluer le temps de travail pour redresser les données
- [x] Faire un retour à Gestibase

Mail du vendredi 23-09-22 15h05

**Comment by stephane-ruhlmann** [comment]
Réponse faite par mail ✅
