### ISSUE TITLE
Exploration et estimation Maquettes HP avec tunnel de connexion user pilotes + OF

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1827]
**Objectif**

_Nous avons modifié le parcours OF sur la HP. Demain tout utilisateur doit pouvoir se connecter à son compte et accéder aux fonctionnalités qui correspondent à ses droits._

**Definition of done**

- [ ] Identification des pages impactées
- [ ] Pages comptes utilisateurs évolutives
- [ ] Proposition d'un parcours HP --> compte
- [ ] Présentation au PO @MelanieRAPHAEL

**Comment by Anne-Camille** [comment]
non reprise telle quelle new kanban => https://github.com/mission-apprentissage/flux-retour-cfas/issues/2001
