### ISSUE TITLE
Vérifier l'expiration du token d'authentification des utilisateurs à la navigation sur les pages protégées

### ISSUE THREAD

**Issue by stephane-ruhlmann** [mission-apprentissage/flux-retour-cfas#1843]
**Objectif**

Aujourd'hui lorsqu'un utilisateur tente d'accéder à une page "protégée" (nécessitant d'être connecté), on vérifie l'existence d'un token dans le local storage :

* S'il n'y a pas de token : on redirige l'utilisateur vers la page de login
* S'il y a un token : on laisse l'utilisateur accéder à la page

Le problème actuel est que le token d'authentification peut avoir expiré (la validité actuelle est de 24h) mais il est tout de même présent, on laisse donc le navigateur accéder à une page protégée mais les requêtes effectuées vers l'API pour récupérer des données (par exemple le nombre d'apprentis) sera invalide (erreur 401) car le token est invalide. L'erreur est gérée dans le front et on redirige l'utilisateur vers la page de login.

Ces erreurs 401 représentent la majorité des messages dans nos logs et l'expérience utilisateur n'est pas optimale car il pense arriver sur une page consultable mais il se fait rediriger vers la page de login.

Ce qu'on doit faire :
* Augmenter le délai d'expiration du token (7 jours ?)
* Vérifier la validité du token en plus de son existence lors de la navigation sur une page protégée

**Definition of done**

- [ ] _L'expiration du token est passée à x jours (à discuter)_
- [ ] _Lors de la navigation sur une page protégée, un token expiré ne permet pas l'accès (utilisateur redirigé sur page de login)_

**Comment by stephane-ruhlmann** [comment]
Validité du token passée à 7 jours dans l'infra : https://github.com/mission-apprentissage/flux-retour-cfas-infra/pull/169

**Comment by stephane-ruhlmann** [comment]
Petit refacto : https://github.com/mission-apprentissage/flux-retour-cfas/pull/1872

**Comment by sbenfares** [comment]
> > @sbenfares l'expiration du token est paramétrable via la config mais écrasée nulle part sur les confs prod/recette/dev, on fallback donc sur 24h ce qui me paraît très court
> > Tu en penses quoi de passer à 7 jours ?
> 
> Oui effectivement on se traine ce truc depuis un bail bien vu

Pour la durée de 7 jours je me demande s'il faut pas creuser l'usage fait par les utilisateurs...
Est-ce que 30 jours serait pas plus confortable ?
