### ISSUE TITLE
Pour provison Sprint 17 octobre

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1844]
- [ ] présentation des données : point Samir x Stéphane x Alexis Sprint 2 octobre

- [ ] certification de comptes OF : Mélanie x Samir x LBA - François et Dimitri (objectif : éviter les validations manuelles de compte, et s'inspirer de ce qui est sécurisé côté LBA)

@stephane-ruhlmann 
@MelanieRAPHAEL

**Comment by Anne-Camille** [comment]
non reprise new kanban : point remplacé par point avec Jady + autre élément repris sur la https://github.com/mission-apprentissage/flux-retour-cfas/issues/2048
