### ISSUE TITLE
créer les maquettes parcours Sifa - entre le 18/10 et le 24/10

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#1888]
Les maquettes du parcours Sifa sont prêtes pour intégration Dev

A partir de la documentation :
- [x] Les maquettes du parcours Sifa sont faites
- [x] Les maquettes sont validées par PO
- [x] Les maquette sont présentées à @sbenfares pour intégration

TO DO : 
Ecran 1 : Accueil OF

- [x] Dans l'encart "la situation de votre établissement" : Ajouter les relations entre OF Responsable/Formateur dans le Référentiel : https://referentiel.apprentissage.onisep.fr/organismes/90506056200022/relations 
Définition à intégrer dans une info bulle ou autre système d'affichage : 
"Relations entre les organismes : 
Les relations entre les organismes sont identifiées via le Catalogue des formations en apprentissage (base des Carif-Oref)
Elles sont identifiées au niveau de l'offre de formation en apprentissage collectée par les Carif-Oref. En effet, chaque offre de formation est associée à un organisme responsable et un organisme formateur (chacun est connu par son SIRET et son UAI le cas échéant).
Si les organismes associés à une offre de formation ont le même SIRET, on en déduit la nature "responsable et formateur" et on ne génère pas de relation.
Si les organismes associés à une offre de formation n'ont pas le même SIRET, on en déduit la nature "responsable" pour l'un et "formateur" pour l'autre, et on génère une relation entre eux.
Si cette donnée est inconnue ou incorrecte, voir la marche à suivre (intégrer lien : https://referentiel.apprentissage.onisep.fr/corrections?item=relations)"

Ecran 2 : tableau des variables
- [x] Pagination
- [x] Offrir la possibilité d'afficher plus de lignes à l'utilisateur
- [x] Faire apparaitre des cellules à corriger en rouge avec balise d'alerte
- [x] Afficher les lignes à corriger en premier
- [ ] Faire apparaitre des filtres à chaque colonne (pour chaque variable) : classement par ordre croissant
- [x] Maquette animée avec système de tempo ? = Permettre la correction de cellule => une fois corriger appuyer sur Entrer ou cliquer en dehors de la cellule => la cellule passe en couleur verte pour indiquer à l'utilisateur la bonne prise en compte de la correction et du bon format => Puis, passage de la cellule corrigée en gris

Documentation 👍 Docs :  
- [x] Parcours Sifa : 
https://whimsical.com/parcours-sifa-4xYrYgxi9Hrc9i6sfAv5q5 
- [x] Pré-maquette Google Slide :  
https://docs.google.com/presentation/d/1AUOgAfQbyw9-bjmvcBYjVI-_n4Onc3YXWf2-ZPs4qv4/edit#slide=id.p  
- [x] Maquette PS
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=5430%3A118524

**Comment by RaphBeta** [comment]
@ClemLan : merci d'avance pour les évolutions de la maquette.
Pour info, Samir démarre les travaux d'intégration à compter de jeudi après-midi.
Je reste à ta dispo si la carte est pas claire. Bon courage !

**Comment by ClemLan** [comment]
[👉 Lien pour parcours et animation sur les cellules en erreur ](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=6759%3A185834)
