### ISSUE TITLE
Supprimer ou archiver les dossiersApprenants avec siret invalides

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1933]
A prévoir après étapes fiabilisation UAI-Siret

**Objectif**

Identifier et supprimer les dossiersApprenants ayant des sirets invalides.
Garder dans une collection ces dossiers pour pouvoir éventuellement prendre une décision (communication auprés des ERPs/CFA?)

**Definition of done**

- [ ] Un script existe qui permet de supprimer les dossiersApprenants avec un siret invalide de la collection et les stocker dans une collection dédiée (pour analyse), fréquence à définir avec les dev (1 fois par mois)

**Comment by Anne-Camille** [comment]
doublon avec https://github.com/mission-apprentissage/flux-retour-cfas/issues/1920 ?

**Comment by Anne-Camille** [comment]
@sbenfares one st en vue de BL avec Nadine, est-ce que selon toi cette carte serait tjs d'actu ?

**Comment by sbenfares** [comment]
> @sbenfares one st en vue de BL avec Nadine, est-ce que selon toi cette carte serait tjs d'actu ?

"one st en vue de BL" j'avoue ne pas comprendre cette phrase 🥲 
Mais on peut, avec @felixat13 sortir via Metabase la liste des données envoyées avec des sirets invalides je pense
Donc la carte peut rester, a voir coté métier ce que vous souhaitez en faire (contact des of ?)

**Comment by Anne-Camille** [comment]
@sbenfares j'ai écrit avec mes pieds désolée ^^' : je voulais dire "on est en revue de backlog". La liste permettrait de communiquer auprès des OF au titre des remontées de listes d'erreurs à corriger.

**Comment by sbenfares** [comment]
> @sbenfares j'ai écrit avec mes pieds désolée ^^' : je voulais dire "on est en revue de backlog". La liste permettrait de communiquer auprès des OF au titre des remontées de listes d'erreurs à corriger.

Ok du coup on prends la carte avec @felixat13.
Je lui montrerais comment sont organisées les données.

**Comment by svengau** [comment]
@sbenfares, toujours d'actualité ?

**Comment by sbenfares** [comment]
> @sbenfares, toujours d'actualité ?

Oui toujours d'actualité ✅
