### ISSUE TITLE
Sommaire "Journal des évolutions"

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1935]
**Objectif**

Faire descendre le sommaire avec la page (sticky) pour faciliter la navigation.

**Definition of done**

- [x] sticky
- [x] déroulé en mode lent (pas de "saut" -> plus facile pour évaluer sa progression dans la page).

**Comment by ClemLan** [comment]
(ma carte) non prio, ce sera à voir avec la refonte de la page (pour l'instant, je garde pour m'en rappeler si la refonte est trop repoussée et si temps, à voir si vraiment utile)
