### ISSUE TITLE
Afficher commune entreprise et OF dans l'export rupturants / abandons

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1958]
**Objectif**

_Pouvoir suivre voire orienter les jeunes vers des centres de formations et/ou entreprises plus proches pour éviter le décrochage pour l'abandon (besoin exprimé par la DREETS BFC)_ (https://github.com/mission-apprentissage/flux-retour-cfas/issues/1967)

**Definition of done**

- [ ] Récupération du code postal + libellé commune entreprise
- [x] Récupération du code postal + libellé commune OF
- [ ] Ajout de deux colonnes "commune entreprise" et "commune OF" dans l'export 

retrouver la commune : possibilité d'utiliser le référentiel pour l'OF, l'API SIrene pour l'entreprise (demande la base siret)

**Comment by stephane-ruhlmann** [comment]
* commune entreprise : nous n'avons pas la data, il nous faudrait collecter le SIRET de l'employeur
* commune OF : idem nous n'avons pas la data, on peut la récupérer depuis le référentiel en cas de SIRET unique et existant (champ "localite")

**Comment by felixat13** [comment]
@Anne-Camille si cela concerne l'export disponible sur le front, c'est plutôt du dev.. Si c'est pour avoir un export dispo sur Metabase je peux avoir l'adresse de l'OF, mais je n'ai aucune info sur l'entreprise actuellement.
