### ISSUE TITLE
Identification des goals Plausible pour le suivi des parcours

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1959]
**Objectif**
Mettre en place un suivi de l'usage du TDB, Etre en mesure de pouvoir suivre les utilisations du TDB (pages consultées, fonctionnalités utilisées)

**To do**

- [x] atelier à prévoir PO/Félix/Ux pour identifier les métriques que l'on veut suivre et les funnels que l'on veut mettre en place (à alimenter ici : éléments listés [ici](https://docs.google.com/spreadsheets/d/1LZlgKV6VPOj3-YYgIUWjAst6eHSVF_RN8yaak4NYz98/edit)
- [ ] dev les demandes
- [ ] afficher les éléments dans la page stats de suivi (footer)

**Comment by felixat13** [comment]
Page Notion plan de tracking : https://www.notion.so/mission-apprentissage/Plans-de-tracking-86c1845affea4d759fc022093af95837?v=64f4c775c7f24f3f9082b59b83db9956

**Comment by felixat13** [comment]
Plan de tracking partagé aux devs pour le développement
