### ISSUE TITLE
PS - Définir quoi suivre sur MB

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#1974]
Suivi des nouveaux envois et nouvelles créations de compte 

- [ ] Définir quoi suivre
- [ ] Maquette tableau
- [ ] Cartes dév pour le Metabase
- [ ] Accès au suivi PS via page stats (à prévoir)

**Comment by cathbaiona** [comment]
@MelanieRAPHAEL je n'ai pas compris les maquettes Tableau et ce que je suis censée faire :-(
