### ISSUE TITLE
Construire une page publique Notion  "Documentation"

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1989]
**Objectif**

Centraliser les ressources pour communiquer un lien à chaque contact, tout en allégeant la charge de dev front.

Accessible depuis le footer du front TDB, pourrait être alimentée par PM et PO en autonomie avec des ressources par cibles (celles utilisées fréquemment dans le cadre de nos contacts), notamment  :
•       un toggle ERP prospects : docs utiles et demandés à chaque fois, comme par exemple les docs API, des FAQ, des docs commerciaux
•       un toggle ERP en prod ou en passe de l'être : argumentaires pour les CFA, éléments de langage pour qu'ils communiquent auprès ds CFA, exemples de tutoriels réalisés par les ERP (à voir si diffusion large ok ou pas pour eux) etc...
•       un toggle CFA : docs commerciaux, argumentaires , FAQ

- [x] Capitaliser les contenus : https://docs.google.com/spreadsheets/d/1F0F65J6H6XJqhcBvRAAW5zpblsn3P5y8QZnNExwltmY/edit?usp=sharing
- [x] Créer la page Notion : https://www.notion.so/mission-apprentissage/Documentation-dbb1eddc954441eaa0ba7f5c6404bdc0
- [x] Voir avec Clemence ou positionner la page (footer ou ailleurs ?) => proposition nouvel onglet documentation regroupant FAQ + doc => décision dans le footer
- [x] Carte dev à faire pour lien vers la page Notion (page publique)
- [x] Communiquer auprès de nos partenaires sur l'existence de la page (?)

**Comment by ClemLan** [comment]
Commencé à faire quelque chose de simple à faire évoluer : [ Page notion](https://www.notion.so/mission-apprentissage/Documentation-dbb1eddc954441eaa0ba7f5c6404bdc0)

Pas favorable à rajouter quelque chose sur le footer : trop d'infos tue l'info en plus les utilisateurs ne le voient pas toujours (tests U) -> proposition : rajouter un onglet "documentation" à la navigation principale (on pourrait même y lier la FAQ)

**Comment by ClemLan** [comment]
Lié à #1622

**Comment by Anne-Camille** [comment]
@Julianne-Lagadec si tu peux regarder la page Notion sur le fond documentaire et voir s'il y a des cibles + docs à y ajouter suite à tes différentes rencontres ce serait topitop !

**Comment by Anne-Camille** [comment]
@ClemLan ok vu ta remarque pour l'onglet doc+faq qui permettrait en plus de bien "ranger" certaines questions par rapport aux profils d'utilisateurs. 

@pabloHry @sbenfares on a maintenant 2 options, sachant qu'on prendra celle qui nous permettra d'aller le plus vite s'il y avait une grosse différence d'estimation entre les deux :

****option 1** on met un lien dans le footer** qui débranche vers la page notion qui est donc en accès public (et on fait une carte en backlog pour faire l'onglet qui va bien + tard dans la roadmap avec intégration complète du fonds documentaire)
**option 2 on créé un nouvel onglet "FAQ et Documentation"** dans lequel on retrouve la FAQ + le lien vers la page notion qui est en accès public (et on fait une carte en backlog pour bien ranger la FAQ et avoir une intégration complète du fonds documentaire plus tard)
est-ce que selon vous l'effort de dev est identique entre les 2 (et donc option 2) ou l'un est plus rapidement livrable (et donc option la plus rapide) ?

**Comment by sbenfares** [comment]
> @ClemLan ok vu ta remarque pour l'onglet doc+faq qui permettrait en plus de bien "ranger" certaines questions par rapport aux profils d'utilisateurs.
> 
> @pabloHry @sbenfares on a maintenant 2 options, sachant qu'on prendra celle qui nous permettra d'aller le plus vite s'il y avait une grosse différence d'estimation entre les deux :
> 
> ****option 1** on met un lien dans le footer** qui débranche vers la page notion qui est donc en accès public (et on fait une carte en backlog pour faire l'onglet qui va bien + tard dans la roadmap avec intégration complète du fonds documentaire) **option 2 on créé un nouvel onglet "FAQ et Documentation"** dans lequel on retrouve la FAQ + le lien vers la page notion qui est en accès public (et on fait une carte en backlog pour bien ranger la FAQ et avoir une intégration complète du fonds documentaire plus tard) est-ce que selon vous l'effort de dev est identique entre les 2 (et donc option 2) ou l'un est plus rapidement livrable (et donc option la plus rapide) ?

Le plus rapide serait le lien en footer d'après ce que je comprends.
Bon après la création de l'onglet est pas couteuse non plus.

**Comment by MelanieRAPHAEL** [comment]
@sbenfares quand tu dis pas couteuse, c'est à dire ? j'ai du mal à évaluer 

@ClemLan @Anne-Camille Petite question sur "organisme de formation" : on a des infos directement sur l'API
peut-être un peu plus tard car ça me parait plus adapté pour l'ERP.
