### ISSUE TITLE
Page stats de suivi interne TDB

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1998]
**Objectif**
Bâtir une page stats interne de suivi d'usage du tdb ; cf atelier irl.
Dans le footer du TDB

**To do**
Maquetter la page, avec 4 onglets : 
- usage
- support
- admin
- Tech (accès admin uniquement)

=>(https://docs.google.com/spreadsheets/d/1LZlgKV6VPOj3-YYgIUWjAst6eHSVF_RN8yaak4NYz98/edit?usp=sharing)

Ces pages pourront comporter des graphiques type histogramme, pie chart, etc. et pour certaines de simple liens vers metabase par ex, ou slack pour le suivi alerting (onglet admin).
Prévoir le cas où la stat n'est pas encore affichée  (bientôt disponible).

**Comment by ClemLan** [comment]
@cathbaiona tu as commencé quelque chose je crois ?

**Comment by ClemLan** [comment]
Vu avec avec @cathbaiona : je l''assigne aussi à cette carte car nous devions, suite à l'IRL d'octobre : 

- [ ] Mettre au propre les travaux de l'équipe Cath (wireframe)
- [ ] Mettre au propre les travaux de l'équipe Clem (wireframe)
- [ ] Créer des pré-maquettes - Cath
- [ ] Créer des pré-maquettes - Clem
- [ ] Mettre en commun les deux
- [ ] Proposer une version commune

**Comment by cathbaiona** [comment]
Anne-Camille, les maquettes ont avancé (mais pas finalisées): https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=4723%3A100948
Est-ce qu'on peut planifier un point toutes les 3 avec @ClemLan ?

**Comment by Anne-Camille** [comment]
@cathbaiona j'ai créé la carte tech Page stats V1 ; on aura donc une première version qui reprendra le design global mais qui sera partiellement livrée. 
La V2 complète sera construite à l'aide du data analyst.
