### ISSUE TITLE
Page stats de suivi d'usage TDB

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#1999]
**Objectif**

Avoir une page stats de suivi d'usage du tdb, reprenant impact et visitorat.

**To do**

Réaliser la dataviz via les requêtes metabase des mesures suivantes (onglet 1)
https://docs.google.com/spreadsheets/d/1LZlgKV6VPOj3-YYgIUWjAst6eHSVF_RN8yaak4NYz98/edit?usp=sharing

Construire la maquette de la page stats qui sera accessible en footer.

**Comment by RaphBeta** [comment]
@Anne-Camille concernant cette carte, il faut la remettre en backlog n'est-ce pas ? Car nous n'aurons pas de travaux data analyse avant l'arrivée Félix si j'ai bien compris ?

**Comment by Anne-Camille** [comment]
archive, reprise des éléments dans https://github.com/mission-apprentissage/flux-retour-cfas/issues/2296
