### ISSUE TITLE
Organiser un atelier / des itw utilisateurs autour de la connexion à un compte : habilitations, partage de compte

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2001]
**Objectif**

Recueillir les usages et besoins concernant les comptes de connexion 

- [ ] au sein d'un même organisme, 1 compte avec partage ? plusieurs comptes ? qui peut être amené à faire quoi parmi les différentes fonctionnalités du TDB (accès aux chiffres, téléversement de données, correction de données, accès aux listes nominatives, ...)
- [ ] session reste-t-elle ouverte ?
- [ ] mot de passe perso ou généré auto ? utilisation d'une vault ?  quels autres comptes avec accès SSO (ex : agent connect, france connect, ...) ?

**Attendu**

1 seule connexion sur TDB, permettant d'accéder, de façon contextualisée selon le profil, à rien ou à tout ou partie

- [ ] des données de pilotage => accès possible à metabase , connexion plus légère possible (via lien magique par ex).
- [ ] des listes nominatives => la connexion doit être à sécurité renforcée
- [ ] des fonctionnalités de téléversement de données, correction des données
- [ ] des fonctionnalités de génération sifa

**Comment by cathbaiona** [comment]
@Anne-Camille Est-ce que cette tâche peut se faire dans le cadre d'un premier travail/sujet avec la communauté de beta-testeurs ?

**Comment by Anne-Camille** [comment]
@cathbaiona oui 
absolument, d'où le tag "ux-ateliers" !

**Comment by Anne-Camille** [comment]
@cathbaiona @ClemLan => pouvez-vous estimer le temps nécessaire
