### ISSUE TITLE
Communauté beta testeurs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2004]
**Mener une réflexion sur la création d'une communauté de beta testeurs**

**Definition of done**

- [x] voir avec Julianne & Jérémy (communauté déjà en cours de construction via LinkedIn)
- [ ] _définir les différentes typologies de beta testeurs, leurs caractéristiques,
- [ ] Identifier les enjeux pour TDB à créer une communauté de BT et modalités d'animation

@cathbaiona

**Comment by Anne-Camille** [comment]
@cathbaiona si tu peux estimer stp !

**Comment by cathbaiona** [comment]
@nadinelouchart j'ai fait la maquette concernant le volontariat des beta-testeurs : 
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A287605&t=ewgqoZpvdWmLQbVv-1
On peut en discuter semaine prochaine, mais à ce jour, je me repose uniquement sur mes contacts privilégiés que j'ai tissé depuis Juillet dernier. Ce serait en effet bien de l'élargir un peu pour ne pas solliciter toujours les mêmes OF, etc...
