### ISSUE TITLE
Metabase - CVL - requête des rupturants qui ont rompu leur contrat depuis 3 à 6 mois

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2014]
**Objectif**

_Permettre à la cellule apprentissage CVL d'identifier les rupturants en situation critique et intégrer cette donnée pour la constitution de la cellule apprentissage de septembre + pousser le sujet au CREFOP_

**Definition of done**

Vérifier si la requête initiale est tjs ok ; si nok, ajuster

- [ ] Requête Metabase Metabase : CVL - Nombre de rupturants qui ont rompu leur contrat depuis 3 à 6 mois + liste nominative protégée dans un sous-dossier
- [ ] Mettre dans le Tableau CVL Metabase le nombre et dans un sous dossier la liste nominative
- [ ] Informer Alisonne Delorme et faire le tableau RGPD -> @MelanieRAPHAEL 
- [ ] Ajouter dans le Tableau de suivi des expérimentations -> @RaphBeta ou @MelanieRAPHAEL

**Comment by stephane-ruhlmann** [comment]
Estimation : 0.5 jour idéal

**Comment by stephane-ruhlmann** [comment]
Estimation : 0.5 jour idéal

**Comment by stephane-ruhlmann** [comment]
Fait ici : https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/97-cvl-rupturants-entre-3-et-6-mois
Seuls les utilisateurs du groupe CVL ont accès à la collection (questions + tableau de bord)

**Comment by MelanieRAPHAEL** [comment]
Merci @stephane-ruhlmann 
Info envoyée à la DREETS CVL, proposition d'échange pour avancer sur l'XP
