### ISSUE TITLE
Crefal - UAI rattachement FormaSup PACA

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2021]
Lorsque la vue réseau sera développée : 

Le Crefal ne souhaite pas que nous diffusions sur TDB les numéros UAI de leurs UFA.
Le seul numéro UAI à diffuser est 0754458N.

=> à décider : TDB = service à la carte pour chaque réseau ?

- [ ] contacter M. Fidelis pour creuser le besoin

Souhait du réseau : à partir de la liste du fichier ci-dessous, créer une vue Réseau CREFAL : 
Additionner les données de tous les UAI et les afficher l'UAI Responsable Campus Montsouris 0754458N
Et faire apparaitre la ventilation par UAI formateur 
https://drive.google.com/drive/folders/1lSHT5Toqwu1BcCy7ggaV_C4zFtjtyf0P 

contact : n.fidelis@cerfal.fr

**Comment by nadinelouchart** [comment]
mail envoyé le 15/03 via la boite support
