### ISSUE TITLE
SUPPORT - écart chiffres MFR l'hebergement - Gestibase

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2029]

**Comment by RaphBeta** [comment]
- [ ] Rechercher à quoi est dû l'écart constaté par la MFR lhebergement

- [ ] Répondre à la MFR

0851286L

Bonjour,

Est-il possible de faire une vérification pour notre établissement sur le nombre de nos apprentis.

En effet, il semblerait que pour 2 élèves en CAPA2, leur rupture ne soit pas prise en compte.

Ci-dessous, notre message envoyé à GESTIBASE.

D'avance merci

cordialement
Lydie Rousseau

**Comment by stephane-ruhlmann** [comment]
Apprenants transmis du 17 au 22 août puis plus rien : https://cfas.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzQsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsODkzLG51bGxdLCIwODUxMjg2TCJdLFsiPSIsWyJmaWVsZCIsODc4LG51bGxdLCI1MDMyMTEzMCJdLFsiPSIsWyJmaWVsZCIsOTAxLG51bGxdLDJdLFsiPSIsWyJmaWVsZCIsODkwLG51bGxdLCJNQVRUSElFVSIsIkJBUFRJU1RFIl1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=

Réponse faite par mail.
