### ISSUE TITLE
SUPPORT - traiter ecart de résultat MFR Saint Meen Le Grand

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2030]

**Comment by RaphBeta** [comment]
Identifier d'où vient l'écart de statut décrit par la MFR
Répondre à la MFR

Bonjour,  je me permets de venir vers vous car je viens de demander à Gestibase pourquoi les éléments que je vois sur IMFR dans le tableau de l'apprentissage ne sont pas exacts.  Je vous laisse les échanges de mails afin de voir le soucis ; Merci pour votre retour. Cordialement.
Saint Meen Le Grand 

Mail ici : 
https://webmail.alwaysdata.com/roundcube/?_task=mail&_mbox=INBOX

**Comment by stephane-ruhlmann** [comment]
Pour retrouver plus facilement : mail de Muriel Roche du 17/10/2022

**Comment by stephane-ruhlmann** [comment]
Les apprenants posant problèmes ne sont en effet plus transmis : https://cfas.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzQsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsODg1LG51bGxdLCJnZXN0aSJdLFsiPSIsWyJmaWVsZCIsOTA1LG51bGxdLCIxMTA5MDIzODhFQSIsIjExMDM1NTM3N0dKIiwiMTgzMDgxMjQwRkMiXSxbIj0iLFsiZmllbGQiLDkxMSxudWxsXSwiMjAyMi0yMDIyIiwiMjAyMi0yMDIzIl1dfSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6bnVsbH0=

Réponse faite par mail
