### ISSUE TITLE
Mise en ligne CGU

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2034]
**Objectif**

_Mettre en ligne la page CGU (voir qui prend si on met @pabloHry ou @stephane-ruhlmann en fonction de la bande passante)_

**Definition of done**

- [ ] attente validation du juridique (demande de relecture envoyée le 17/10/2022) => échange avec Osiris 21/10, revient vers nous début nov.
- [ ] La page CGU est en ligne et accessible depuis le footer
- [ ] Le design de la page CGU est identique à celui de la page Mentions légales (homogénéité des écrans)
- [ ] Les champs de mise à jour (date) sont dynamiques
- [ ] La mise à jour des CGU est reportée dans le journal des évolutions

Dépendances : Maquette https://github.com/mission-apprentissage/flux-retour-cfas/issues/1058 @ClemLan et texte https://github.com/mission-apprentissage/flux-retour-cfas/issues/1676  et validation https://github.com/mission-apprentissage/flux-retour-cfas/issues/1780 @Anne-Camille

**Comment by MelanieRAPHAEL** [comment]
J'imagine qu'il est trop tôt pour avoir des nouvelles d'Osiris
Est-ce qu'on peut envisager le passer en sprint 3 ou 4 ? @Anne-Camille

**Comment by ClemLan** [comment]
Lié à #2086
