### ISSUE TITLE
FormaSup PACA pour connexion TDB

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2035]
- [x] revenir vers L.  Dupaty pour lui dire go + l'informer de l'échéance nouveau schema de données + demander les données qu'il manipule (pour comparaison avec schema V2) => ok mail envoyé le 02/11, à suivre fin de sprint sinon relance.

Suite au mail de relance fait par @RaphBeta, répondre à Monsieur Dupaty pour acquisition données : 

Mail dans TDB : @[cfa-epure.com]
Bonjour Raphaëlle, oui oui la connnexion a l api est prête et je n ai plus qu'à mettre en place la partie export des effectifs. J attends la confirmation de votre part que vous êtes à jour puisque j avais retenu qu une maj de l api devait être déployée fin septembre début octobre
Cdt Laurent Dupaty

**Comment by RaphBeta** [comment]
@Anne-Camille quel est la cible de la mise en prod du schéma de données V2 ? 
C'est pour savoir si je dis à FormaSup PACA de nous envoyer les données en s'appuyant sur le schéma actuel ou si on le fait patienter.
Merci à toi.
