### ISSUE TITLE
Mesurer la fréquence de téléchargement de chacune des listes mise à disposition (requête MB)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2036]
requête metabase sur le volume de téléchargement des listes 
(par utilisateurs + agrégats sur l'ensemble de la DREETS = tous les utilisateurs identifiés de la DREETS de cette région)

Répartition des téléchargements par : 

- Type de liste 
- Utilisateur + sa région

- dataviz

**Comment by sbenfares** [comment]
Visible ici : https://cfas.apprentissage.beta.gouv.fr/metabase/question/375-statistiques-de-telechargements-des-listes-par-typologie-dutilisateurs-date
