### ISSUE TITLE
Mesurer la fréquence de connexion des agents DREETS sur le TdB (requête MB à faire)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2037]
tracking des logs selon la fréquence d’usage constatée chez les utilisateurs) sur Metabase

**Objectif**

_Afficher dans MB le nombre de connexions mois par mois pour les utilisateurs de type DREETS._

**Definition of done**

- [ ] _Création de la requête MB_
- [ ] Dataviz

**Comment by sbenfares** [comment]
Disponible ici : https://cfas.apprentissage.beta.gouv.fr/metabase/question/374-nombre-de-connexions-dutilisateurs-de-type-dreets-par-mois

**Comment by MelanieRAPHAEL** [comment]
Nickel et placé dans la collection : https://cfas.apprentissage.beta.gouv.fr/metabase/collection/46-mesures-dimpact
