### ISSUE TITLE
Modifier règle de tri affichage des listes (N/A en dernier)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2047]
Ajouter une règle dans le tri par ordre alphabétique qui mette les résultats N.A. en bas des listes 
==> Par ordre alphabétique une chaîne vide « » (absence de libellé) passe en dernier.

@sbenfares 
@pabloHry

**Comment by stephane-ruhlmann** [comment]
Estimation : 1 jour idéal

**Comment by svengau** [comment]
@Anne-Camille cette carte est assez ancienne, toujours d'actualité ? Si oui, de quelle liste parle-t'on ?
