### ISSUE TITLE
Sécurisation de comptes  : garantir l'identité de l'utilisateur

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2048]
certification de comptes OF : Mélanie x Samir x LBA - François et Dimitri (objectif : éviter les validations manuelles de compte, et s'inspirer de ce qui est sécurisé côté LBA)

Sécurisation renforcée nécessaire sur la partie "accès aux listes nominatives"
Sécurisation plus légère sur autres accès (par ex via lien magique)

**Comment by MelanieRAPHAEL** [comment]
rdv France connect à venir
