### ISSUE TITLE
Complétude tableau APIV2

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2053]
D'une façon générale : 
ajouter au tableau les données à recueillir issue de 

- [x] nouveau schema de données
- [x] collab SIEI

=> fait ici : https://docs.google.com/spreadsheets/d/1x0wWPaEmHDsyzjVr9rQNEz9hieSuJKKK/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true

Compléter le tableau API V2 :  

- [x] Colonne A : "Nom du champ" à compléter à partir de la ligne 48
- [x] Colonnes B et C : vérifier format de données et exemples 
- [x] Colonnes F et G existe-t-il une dépendance avec d'autres champs de données ?
- [x] Colonnes M et N : la donnée est-elle fiabilisée dans TDB API V1 ?
- [x] Colonnes Q et R : contrôle API V2 et source de contrôle API V2 (pour les variables obligatoires à minima)

https://docs.google.com/spreadsheets/d/1dW4nqsqg84UEFO-w0FQag25feSd973r8uFxV8c2D4Xs/edit#gid=1282466610

**Comment by Anne-Camille** [comment]
@RaphBeta pourrais-tu stp juste relire la colonne sifa ? (normalement tout y est mais je préfère que tu vérifies) 
@RaphBeta et @MelanieRAPHAEL  pourriez-vous relire la colonne "pilotage cible" ? (pour faire suite à notre atelier schema de données et me dire si j'ai oublié des trucs svp ?

**Comment by RaphBeta** [comment]
Je n'ai pas retrouvé OG, j'ai ajouté dans la dernière ligne du tableau @Anne-Camille 
pour le reste Sifa tout est ok

**Comment by Anne-Camille** [comment]
merci bcp @RaphBeta ; oui c'est quand on a  besoin de la donnée  (donc si tu filtres sur "oui" dans la colonne sifa, tu devrais retrouver toutes tes variables) et IJ c'est inserjeunes en fait c'est ce que va produire l'équipe Trajectoire pro
