### ISSUE TITLE
Ajouter le lien vers un nouvel écran Politique de confidentialité + maj autres docs rgpd

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2080]
**Objectif**

Conformité RGPD (urgent)

**To  do**

- [x] Récupérer le contenu texte auprès d'Osiris 

- [ ] Remplacer l'intitulé du lien "Gestion des cookies" en footer par "Politique de confidentialité", au clic, ouverture d'un nouvel écran qui contient le contenu texte. (Reprendre le design de la page Mentions légales => lien vers doc : https://docs.google.com/document/d/1-C5QsSyazUotOakUTJNCC-SA_tKc2Mpk/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true   

- [ ] Ajout en footer d'un lien "CGU", au clic, ouverture d'un nouvel écran qui contient le contenu du texte. reprendre le design de la page Mentions légales => lien vers doc : https://docs.google.com/document/d/1OWdsZehhR2vQzkR_tJbKUtOxjjQdTohX/edit#heading=h.rjomw3npwerf

- [ ] Dans le footer, remplacer le contenu derrière le lien "Mentions légales" par le contenu de ce doc => https://docs.google.com/document/d/1RwLrc1qBWh4_AgsvcSwx0QQy8R7ueG4V/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true

Chaque page comporte la dernière date de mise à jour du document (prévoir champ dynamique).
Pas besoin de faire des toggle : les doc doivent être imprimables. On peut éventuellement faire un sommaire sticky avec ancres sur les titres contenus mais s'il n'y est pas, ce n'est pas important.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/63646363/207001934-5ad0d356-ec24-49ab-841f-e5db836edbb8.png">

**Comment by stephane-ruhlmann** [comment]
Estimation : 0.5 jour idéal

**Comment by RaphBeta** [comment]
@sbenfares je te laisse prendre en charge et éventuellement déléguer à @pabloHry
