### ISSUE TITLE
SIFA - Formulaire - Variable 4 : statut_apprenant

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2102]

**Comment by RaphBeta** [comment]
Nom variable dans le TDB : statut_apprenant
Nom de la variable à faire apparaître dans le formulaire : Statut du jeune
Variable obligatoire
Format attendu : Format texte. Limiter le champ de remplissage à 6 caractères. Pré remplir par défaut ce champ de “APP”
Contrôle attendu : présence obligatoire. Le format APP est incorrect.
Contenu de l'info bulle : Variable obligatoire. Libellé du attendu “apprenti”, code “APP”

**Comment by sbenfares** [comment]
@RaphBeta discuter ensemble de ce champ, car non présent tel quel dans le TdB
