### ISSUE TITLE
Revoir la page "Comprendre les données"

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2136]
- [ ] Faire des propositions d'évolution wording et visuelles

Travail maquettes en cours : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=4723%3A100948

**Comment by cathbaiona** [comment]
@RaphBeta cette carte est-elle en doublon avec le #1720 ?

**Comment by RaphBeta** [comment]
@cathbaiona oui en effet. J'ai archivé la #1720
