### ISSUE TITLE
SIFA - Création du script de rapatriement donnéesApprenants vers donnéesSifa

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2145]
- [x] Création du modèle
- [ ] Création de la factory & tests
- [ ] Création du component & tests
- [ ] Tracking des erreurs = nombre et champs à chaque création ou modification de l'espace SIFA
- [ ] Création du job & tests
- [x] Création du script infra
- [x] Création du cron infra

**Comment by antoinebigard** [comment]
du coup c'est le modéle SIFA : https://docs.google.com/spreadsheets/d/1x0wWPaEmHDsyzjVr9rQNEz9hieSuJKKK/edit#gid=722212932 ? @sbenfares

**Comment by sbenfares** [comment]
> du coup c'est ça le modéle SIFA : https://docs.google.com/spreadsheets/d/1x0wWPaEmHDsyzjVr9rQNEz9hieSuJKKK/edit#gid=722212932 ? @sbenfares

Non pas entièrement, pour le moment on est sur un sous-ensemble de qqs champs uniquement.
