### ISSUE TITLE
SIFA/PS - Affichage nature des relations OF

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2150]
Maquette SIFA : 
- Sur l'écran 1, afficher les relations entre OF Responsable/Formateur iso affichage dans le Référentiel
https://referentiel.apprentissage.onisep.fr/organismes/90506056200022/relations

=> Lien à faire à la création de compte et l'interface d'accueil (vision produit)
=> Lien à faire avec écran "Bienvenue sur PS"

**Comment by ClemLan** [comment]
@RaphBeta est-ce que ça ne correspondrait pas à ça ? (on l'a toutes les deux sur nos [maquettes](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=6754%3A182828))
<img width="558" alt="Capture d’écran 2022-11-03 à 09 59 35" src="https://user-images.githubusercontent.com/73469494/199681415-423b8825-ddda-4a1b-8c13-d31a78ed1799.png">
