### ISSUE TITLE
Intervention Dreets IDF et OF IDF 15/11

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2155]
Suite interview Dreets IDF, proposition faite pour que le TDB soit mis à l'ODJ d'une réunion à destination des OF d'IDF le 15/11

- [ ] Répondre semaine du 1er novembre à la dreets 
- [ ] Préparer support
- [ ] Assurer le webinaire le 15/11

**Comment by RaphBeta** [comment]
@MelanieRAPHAEL on se redit qui intervient ;-) 
Faudra répondre à la Dreets IDF aussi ! A plus tard

**Comment by MelanieRAPHAEL** [comment]
Ok @RaphBeta lundi on voit ça, la prés DGEFP et Mayotte ?

**Comment by Anne-Camille** [comment]
je classe (date dépassée).
