### ISSUE TITLE
RH - recrutement DEV (entretiens)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2159]
- [x] A/R candidatures reçues => @Anne-Camille 
- [x] revue des candidatures reçues => @sbenfares @stephane-ruhlmann @antoinebigard 
- [x] présélection : faire la liste avec les motifs de refus / inviter à un entretien => @sbenfares @stephane-ruhlmann 
- [x] envoyer les refus  => @Anne-Camille 
- [x] faire passer les entretiens et les tests => @sbenfares @stephane-ruhlmann (@antoine pour les tests ?)
- [x] présenter les résultats entretiens en équipe ?

**Comment by sbenfares** [comment]
Liste des candidats visible dans Notion : Transverse > Recrutements et onboarding > Recrutement Dev Fullstack Tdb - Octobre 2022
