### ISSUE TITLE
Nouvelle HomePage

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2162]
Carte créé dans le nouveau kanaban (à la suite de https://github.com/mission-apprentissage/flux-retour-cfas/issues/1675)

Retours recette au 03/11 : 

- [ ] non bloquant mep : cards de taille différentes 

![Image](https://user-images.githubusercontent.com/63646363/199696489-fcab5543-2c65-4dec-9f43-ed61431e3429.png)
- [x] retirer la phrase "le tableau de bord, c'est" 

![Image](https://user-images.githubusercontent.com/63646363/199697314-06a3a9b0-2414-4b95-9343-d60ded7c933e.png)
et dans ce cas, ajouter des majuscules à chaque début de nouvelle phrase + supprime le point après la dernière pour arriver à ça : 
-Faciliter le pilotage des politiques publiques 
-Accompagner les jeunes en situation de décrochage (et donc d'influencer leur.s parcours scolaires et professionnels) 
-Simplifier les déclarations des organismes de formation auprès des pouvoirs publics

- [x] sur le point "Accompagner les jeunes en situation de décrochage" supprimer " (et donc d'influencer leur.s parcours scolaires et professionnels) " qui est mal rédigé

- [x] faire attention, l'image à côté est longue, ce qui crée un gros espace blanc entre cette partie et la suivante
<img width="188" alt="Capture d’écran 2022-11-04 090412" src="https://user-images.githubusercontent.com/81155379/199923161-f937fda6-e67f-4d79-8e38-93acb36d4152.png">

- [ ] vérifier que ce titre est à la même police/graisse que les précédents (idem "à quoi sert le tdb" ?)

![Image](https://user-images.githubusercontent.com/63646363/199697498-d7f423fc-e106-4694-9a9a-a98c19a5b569.png)

- [x] A qui sert le tableau de bord ? à remplacer par : À qui sert le tableau de bord ? (majuscule avec accent grave)

- [ ] les entrées utilisateurs du tableau de bord ne sont pas à la même taille, il faut uniformiser/harmoniser cette présentation
<img width="922" alt="Capture d’écran 2022-11-04 092734" src="https://user-images.githubusercontent.com/81155379/199927357-f4b83115-152c-4d15-b7ec-e69de0f9825a.png">

- [x] Bloc à supprimer (redondance avec ce qui est indiqué juste en dessous)
<img width="731" alt="Capture d’écran 2022-11-04 084149" src="https://user-images.githubusercontent.com/81155379/199927602-6289b71f-5508-407b-a2fa-57576cf4769a.png">

- [x] Le service tableau de bord de l'apprentissage est porté par la Mission interministérielle pour l’apprentissage. Vous avez besoin d’en savoir plus sur les données collectées, les différents types d’accès aux données, etc. Contacter l'équipe : [tableau-de-bord@apprentissage.beta.gouv.fr](mailto:tableau-de-bord@apprentissage.beta.gouv.fr) -> supprimer : Contacter l'équipe : [tableau-de-bord@apprentissage.beta.gouv.fr](mailto:tableau-de-bord@apprentissage.beta.gouv.fr) (on propose de contacter l'équipe juste en dessous)

**Comment by RaphBeta** [comment]
Evolutions à intégrer dans la maquette :
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=4723%3A100948&t=esy83QgOxKFzDBko-0
+ https://docs.google.com/presentation/d/1_bjiwlag_Z5n4u6UYsdkVkmfL2DNaq6dCGs1G3u1X4o/edit#slide=id.g16e7a2432a8_0_16

@cathbaiona : peux-tu mettre à niveau les maquettes suite à mes commentaires dans la maquette HP new ? Merci beaucoup 😊
