### ISSUE TITLE
Sur ma vue OF j'ai un historique des envois et par quelle source

### ISSUE THREAD

**Issue by MelanieRAPHAEL** [mission-apprentissage/flux-retour-cfas#2187]
En tant qu'OF qui transmet et qui a un compte validé sur TdB, je suis connecté et sur ma vue utilisateur 
j'ai alors accès à la liste des derniers envois et si il a été envoyé par un ERP et lequel ou par partage simplifié
si mon OF a plusieurs comptes habilités à transmettre des données et les visualiser alors tous les membres de cet OF voient l'ensemble des envois et de l'historique

**Comment by Anne-Camille** [comment]
cloturée : obsolète vu retravail du parcours + info source déjà présente
