### ISSUE TITLE
SPEC "Vues utilisateurs"

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2230]
Spécifier les différentes vues utilisateurs dans le TDB.

1/

- [x] Assurer un atelier avec Sofia, Catherine et Raphaelle sur état des lieux existant objets/actions et fonctionnalités du TDB
- [x] Définir tout ce qui peut être vu sur le TDB et tout ce que l'on peut faire sur le TDB actuellement @sofiaboulaarab 
- [x] Raph : vérifier qui sont les utilisateurs qui ont l'accès pilote ? (OPCO ? CR ?)
- [x] regarder le fonctionnement de "gestion des utilisateurs" et "gestion des réseaux CFAs
- [x] voir vision produit et travaux IRL

2/
- [ ] Créer la carte UX/UI pour les maquettes
Vue DREETS : https://whimsical.com/Gu5iHbkE5JtiE4cY9KbW3g

Maquettes Catherine : 
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=4723%3A100948&t=NEUFZlStqveLYaYw-0

**Comment by sofiaboulaarab** [comment]
@RaphBeta 
Pour info il faut distinguer les rôles vs les utilisateurs, je m'explique
- rôle admin = 1 type d'utilisateur = membres MNA
- rôle api = 1 type utilisateur = ERP
- rôle "pilot" = plusieurs types d'utilisateurs = DREETS, CR, cellule apprentissage, académie, etc. (cf capture écran pour liste exhaustive)
- rôle "network" = 1 type utilisateur = tête de réseau
[tout est dans metabase](https://cfas.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjV9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) - 
tu peux aussi consulter la [liste des comptes (sans doute pas à jour)](https://docs.google.com/spreadsheets/d/1NuPnys9jeei938QPRFd8-qTr_mcV1FU_MyRaza0QzPE/edit#gid=0)
<img width="497" alt="Screenshot 2022-11-14 at 18 38 24" src="https://user-images.githubusercontent.com/47563147/201728363-14a8253c-ac95-4700-bcd2-89afed096d72.png">

- ensuite il y a le type d'utilisateur CFA = passe par une URL privée : [tout est dans metabase](https://cfas.apprentissage.beta.gouv.fr/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ[…]YmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
