### ISSUE TITLE
Explorer Ecarts données restituées dans TDB

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2231]
Suite à une alerte du CFA ISCAE Education, explorer les écarts de chiffres entre ce qui est enregistré dans le logiciel de SC Form et ce qui est restitué dans le TDB.

- [ ] Voir exemples d'écart à restituer dans mail envoyé sur la bal TDB et explorer chaque situation
- [ ] Corriger en tant que de besoin les bugs
- [ ] Tenir informé l'OF des résultats et des actions engagées côté TDB

**Comment by stephane-ruhlmann** [comment]
@RaphBeta Je me permets de fermer le ticket, on a répondu avec Anne et faisons passer un fix
