### ISSUE TITLE
Requêtes à créer pour page stats internes

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2240]
Dans le cadre de la création de notre page de pilotage interne, créer les requêtes MB suivantes (vérifier en amont si elles existent ou non) : 

- [ ] Nombre de création de comptes par mois 👉🏼 WIP : https://cfas.apprentissage.beta.gouv.fr/metabase/question/378-nombre-de-creation-de-comptes-par-mois
- [ ] Nombre de création de comptes par type d'utilisateur 👉🏼 WIP : https://cfas.apprentissage.beta.gouv.fr/metabase/question/379-nombre-de-creation-de-comptes-par-type-dutilisateur
- [ ] Nombre d'acteurs utilisant nos données (consommateur de notre API)
- [ ] Liste des OF qui utilisent l'API 
- [ ] Nombre users uniques / mois qui se connectent par mois
- [ ] Nombre users uniques / mois qui se connectent par territoire
- [ ] Typologie d'utilisateurs 
- [ ] Volume Consultation/connexion OF par mois
- [ ] Volume Consultation/connexion OF par territoire
- [ ] Volumes de données transmises par Canal de versement des données des OF : ventilation par ERP et SERP
- [ ] typologie des demandes (anomalie, connexion...) par type d'utilisateur
- [ ] liste des ERP déclarés via le tunnel de connexion (ERP branchés et ERP non branchés)
- [ ] volume de données transmises par ERP (détection pb API) 
- [ ] suivi des logs : par typologie d'utilisateurs, par fréquence, par période  (jour/mois) => je crois qu'une partie de la requête existe déjà
- [ ] nombre de requêtes transmission des données en erreur
- [ ] alerting archivage des données
- [ ] Demandes de créations de comptes par typologie d'utilisateurs 
- [ ]  Demandes de créations de comptes par fréquence
- [ ]  Demandes de créations de comptes par période
- [ ] Volume de données collectées  

Ces requêtes devront ensuite faire l'objet d'une travail d'intégration front au regard des maquettes de @cathbaiona

**Comment by sbenfares** [comment]
@RaphBeta qu'est-ce que tu entends pas "fréquemment" dans 

> Tracking utilisateurs qui utilisent le TDB fréquemment par période

> Tracking utilisateurs qui utilisent le TDB fréquemment par type d'utilisateur

**Comment by sbenfares** [comment]
> @sbenfares : plus. de 2 connexions par an

Par an ?? c'est pas trop peu 🤔

**Comment by RaphBeta** [comment]
et bien je ne connais pas la fréquence de connexion des différents utilisateurs et surtout c'est vraiment variable d'une région à l'autre et selon les utilisateurs. Je te propose de faire la requete comme ca et de voir ce qu'il en ressort. merci beaucoup !
