### ISSUE TITLE
Créer un filtre "Secteur d'activité"

### ISSUE THREAD

**Issue by RaphBeta** [mission-apprentissage/flux-retour-cfas#2288]
Créer sur le TDB un filtre "secteur d'activité" : [WIP](https://docs.google.com/spreadsheets/d/1KIS_J3bnufZKXNtI_XyKidJqZtzRssRl/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true)

- [ ] Sur la base de la correspondance RNCP > formacode : https://www.data.gouv.fr/en/datasets/repertoire-national-des-certifications-professionnelles-et-repertoire-specifique/, nous avons la correspondance RNCP = grand domaine du formacode.
Nous pouvons donc afficher un filtre grand domaine du formacode > sous filtre libellé formacode > sous filtre RNCP ou ensemble de RNCP liés à ce formacode

- [ ] Sur la base de la correspondance RNCP > ROME, nous avons la correspondance RNCP = grand domaine du ROME.
Nous pouvons donc afficher un filtre grand domaine du ROME > sous filtre sous domaine du rome > sous filtre RNCP ou ensemble de RNCP liés à ce ROME

- [ ] en fonction de la pertinence des couples domaines/sous domaines remontés pour un échantillon de RNCP, choisir la table qui définira les filtres pro => edit : on peut afficher les 2 et tracker les usages.

A inclure dans une réflexion globale sur les filtres : 

![Image](https://user-images.githubusercontent.com/63646363/222747776-9177b488-fa45-464d-a3b4-b422d96e86e4.png)

**Comment by Anne-Camille** [comment]
Partir du RNCP
Contact Alexis / table custo
tests avec DREETS CVL/PDL (maquettes à comparer avec filtre ascendant à partir du rncp et filtre descendant à partir du grand domaine d'activité)
comparer avec les filtres utilisés par excellence pro

le filtre et les sous-filtres seraient organisés ainsi : grand domaine (dont domaine support)> sous domaine > liste RNCP

**Comment by Anne-Camille** [comment]
old échange : Plusieurs idées :
 
1/ Source : https://www.education.gouv.fr/codification-des-formations-et-des-diplomes-11270), si on isole les 4e, 5e et 6e chiffres du code cfd, on obtient, la nsf (groupe de spécialité de la nomenclature des spécialités de formation). Et si on a la nsf, on a le formacode qui propose un découpage en 14 grands domaines.https://formacode.centre-inffo.fr/comment-est-organise-le-formacode,45.html 
donc il faudrait dev un script qui isole les chiffres qu'il faut du cfd, et qui se base sur la table de correspondance de ce nsf pour affecter à chaque cfd un des 14 domaines (on peut même pousser à descendre au sous-domaine si on veut être précis).
https://mission-apprentissage.slack.com/archives/D03GET8PZ53/p1669915356285009)
et là du coup t'as ton filtre. (soit 14 entrées, soit + si tu vas au sous-domaine).

2/  => partir du cfd > définir le rncp> définir le ou les rome correspondants au RNCP > récupérer les grands domaines d'activité du ROME

3/ 
on va voir chez LBA dans quels grands domaines (j'en avais fait 147, mais c'était sur la base du ROME/RNCP pour faire se correspondre entreprises et formations) sont rangées les formations (mais pas avec une liste d'organismes, plutôt avec une liste de cfd)
A creuser car : 1 cfd peut avoir plusieurs rncp rattachés et inversement (difficile de se faire parler les mondes du travail et de l'éducation !). Exposer le besoin aux collègues lors de l'irl pour trouver le système le plus efficace


4/ Autre point à creuser : voir côté ONISEP pour obtenir les éléments "secteur activités"

5/ branches professionnelles ?

**Comment by cathbaiona** [comment]
Du nouveau pour le filtre par secteur pro : Pôle emploi a regroupé les ROME en 37 familles pro, ce qui pourrait offrir un niveau intermédiaire intéressant (cela pourrait remplacer domaines et sous-domaines tel qu'on l'envisageait, et on gagnerait ainsi 1 niveau de sous-filtre) : https://candidat.pole-emploi.fr/metierscope/secteurs-activite
