### ISSUE TITLE
Page stats interne : ajout des stats couverture et qualité des données (fiabilité)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2296]
**Origine du besoin**
Avoir l'info du taux de couverture par territoire (+ évolution et modalité de calcul)
Avoir l'info de l'indice de fiabilité par territoire (+ évolution et modalité de calcul) 
Afin de permettre aux opérateurs publics de connaître la représentativité et l'utilisabilité des données de leurs territoires.

**To Do**

- [x] Ajout d'un onglet "Couverture" =>iframe contenant les éléments de [ce dashboard ](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/111-dataviz-taux-de-couverture) / veiller à ne pas faire apparaître la mention "TO DO"
- [x] Ajout d'un onglet "Qualité des données" => iframe contenant les éléments de [ce dashboard](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/112-dataviz-taux-de-fiabilite)

Les [maquettes sont visibles ici.](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=7259%3A219247&t=ldrhno40QMn4JFxs-0)

**Comment by Anne-Camille** [comment]
@felixat13 pour mettre
le [dashboard couverture](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/111-dataviz-taux-de-couverture) derrière l'onglet Couverture
le [dashboard fiabilité ](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/112-dataviz-taux-de-fiabilite)derrière l'onglet Qualité des données 

Avec un iframe, exactement comme pour l'onglet Visitorat (qui affiche Plausible) ; il te faudrait l'appui d'un dev ?

**Comment by felixat13** [comment]
@Anne-Camille oui, ou au moins pour la première fois !

**Comment by Anne-Camille** [comment]
merci @felixat13 @david-nathanael sera le bon interlocuteur pour la mise en place des onglets et de l'iframe.

**Comment by david-nathanael** [comment]
merci @Anne-Camille

@felixat13 Si tu as les liens metabase pour les iframes je suis preneur

**Comment by felixat13** [comment]
Hello @david-nathanael, je remet en forme les dashboards Metabase, et je t'envoie ça dans la journée !

**Comment by felixat13** [comment]
@Anne-Camille est-ce que les dataviz concernant les taux de couvertures ne pourraient pas aller dans l'onglet Acquisition ? (Que l'on pourrait éventuellement renommer Acquisiton & Couverture si besoin). Ou bien on souhaite vraiment distinguer les 2 ?

**Comment by felixat13** [comment]
@david-nathanael iframe dashboard taux de couverture : 
```
<iframe
    src="https://cfas.apprentissage.beta.gouv.fr/metabase/public/dashboard/9808c918-2d2f-4ae5-b0e7-5e1d982e3e66"
    frameborder="0"
    width="800"
    height="600"
    allowtransparency
></iframe>
```

**Comment by felixat13** [comment]
@david-nathanael iframe du dashboard fiabilisation : 
```
<iframe
    src="https://cfas.apprentissage.beta.gouv.fr/metabase/public/dashboard/78bc775c-1be5-4e61-b81c-3fe4679e480b"
    frameborder="0"
    width="800"
    height="600"
    allowtransparency
></iframe>
```

**Comment by Anne-Camille** [comment]
re7 ok @david-nathanael @felixat13
