### ISSUE TITLE
Supprimer les calculs d’indicateurs → passer en passe plat  Redis clear

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2322]
Repenser le système de calcul d'indicateurs : 

- Processus asynchrone avec stockage dans une collection stats
- Suppression de REDIS inutile du coup

**Comment by svengau** [comment]
@sbenfares, toujours d'actualité ? Si oui, peux-tu mettre plus de détails stp ?
