### ISSUE TITLE
Importer le réseau AFTRAL

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2333]
cf https://www.notion.so/mission-apprentissage/Explications-sur-les-fichiers-transmis-aux-t-tes-de-r-seau-pour-expertise-des-liens-entre-les-organi-0a414689df8e4fa9aa64760f131e303c#bf5c07278a8e40a780a7383dacc71cd5

**Comment by Anne-Camille** [comment]
re7 ok
