### ISSUE TITLE
Installer script de fiabilisation inscrits sans contrats non recus depuis plus de 3 semaines

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2344]
=> suppression des inscrits sans contrats sans modif depuis plus de 3 semaines https://mission-apprentissage.notion.site/Fiabilisation-Inscrits-sans-contrat-c60b82dbe1194433aff3471716b3c1d8

**Comment by sbenfares** [comment]
A vérifier coté MB : https://cfas.apprentissage.beta.gouv.fr/metabase/question/983-effectifs-inscrits-sans-contrats-non-recus-depuis?DateDerniereReception=2023-04-25
