### ISSUE TITLE
Non-régression : réinstaller les filtres par département, réseau, formation

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2347]
MEP du 16/01 : 

disparition des filtres vue par département, réseau et formation

=> à réinstaller sur les profils concernés : 

opérateur public : Onglet Mon tableau de bord : filtre vue département / réseau /formation/niveau de formation
réseau : Onglet Mon tableau de bord : vue département / formation/niveau de formation
OF : Onglet Mon tableau de bord : formation/niveau de formation

Lien avec https://github.com/mission-apprentissage/flux-retour-cfas/issues/1916(permettre à un utilisateur Guadeloupe de filtrer sur Guadeloupe/st Martin/St Barth)

=> à ajouter sur la home page : 
filtre par région

**Comment by Anne-Camille** [comment]
@cathbaiona @ClemLan avez-vous des liens vers des maquettes pour la partie front svp ?

**Comment by cathbaiona** [comment]
À ce jour, il existe :
- la version avec les vues telle qu'elle existait avant dans l'onglet "Indicateurs en temps réel" (mais qui va disparaître au profiter de la page "Mon tableau de bord" : https://www.figma.com/file/9GeatEwlABef9OqEZPMvzI/TBA-(Archives)?node-id=11%3A119407&t=5jBrKNhCv1zfHVL8-1
- la version que j'ai testée auprès des DREETS/DDETS pour l'onglet "Mon territoire" : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=8508%3A284424&t=qS64XJp2WKg9VTV6-1
Je dois donc créer vendredi les maquettes pour cette version intermédiaire.

**Comment by cathbaiona** [comment]
Les maquettes sont ici :
- DREETS : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9434%3A274460&t=mvHXiH8yh81Cas6Z-1

**Comment by Anne-Camille** [comment]
- [ ] retirer le filtre "France entière" de la vue territoriale
- [ ] wording : remplacer le libellé d'onglet "effectifs par formation" par "effectifs par niveau" de la vue territoriale


![Image](https://user-images.githubusercontent.com/63646363/222160806-502d0b41-97d2-413a-8e10-4ad88546dc35.png)

- [ ] un utilisateur région a accès par défaut à sa région + départements qui la composent / un utilisateur département a accès par défaut à son département + aux autres départements de la région => on ne permet pas un accès à des régions ou départements limitrophes hors région (dans la version actuelle, avant atelier sur les vues et permissions).
