### ISSUE TITLE
Page d'accueil V2

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2348]
**Origine du besoin**
Rendre la page d'accueil plus attractive grâce à :
- de la dataviz
- un filtre région supplémentaire pour afficher de la donnée dynamique

**To DO**

- [x] définir ce que doit contenir la page d'accueil : atelier PO/UX/DATA à organiser

**Comment by nadinelouchart** [comment]
Revoir la page d'accueil actuelle. fait par @cathbaiona 

Maquettes Figma disponibles ici (Chantier en cours) : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?type=design&node-id=5054%3A115864&t=keEyCkylGlLnu8rj-1
