### ISSUE TITLE
Remplacer le bouton flottant aide par un onglet Infos

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2349]
**Origine du besoin**

Suite MEP 16/01 : centralisation et rationalisation des infos sur une page Notion publique Documentation, accessible via un bouton flottant présent sur toutes les pages.
Souhaité : mieux intégrer les infos/docs dans les parcours

**To do**
Réaliser une maquette avec un onglet supplémentaire "Questions ?" (ou Aide)  tel que présent[ sur le site macantine](https://ma-cantine.agriculture.gouv.fr/accueil)
Le menu déroulant comporte : 
- la FAQ avec le [lien vers la page documentation](https://www.notion.so/Documentation-dbb1eddc954441eaa0ba7f5c6404bdc0)
- un lien vers une page "ressources" dédiée avec tous les guides d'utilisation et les tutos vidéos (à construire)

**Comment by cathbaiona** [comment]
Maquette header avec "Questions ?" 
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=7480%3A260428&t=InS0uAyztLuQvl9p-1

**Comment by Anne-Camille** [comment]
carte dev => https://github.com/mission-apprentissage/flux-retour-cfas/issues/2875
