### ISSUE TITLE
Import des effectifs : Ajouter un nouvel apprenant (à la main)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2350]
**Origine du besoin**
Concerne la vue OF (responsable-formateur et formateur)
Les CFA sans ERP qui n'ont que peu d'apprentis dans leurs effectifs peuvent aujourd"hui importer leurs infos via un template de fichier qu'on leur propose de télécharger > remplir > téléverser

Souhaité : leur offrir la possibilité d'ajouter manuellement directement dans l'interface

**To DO**
Reprendre les devs qui ont été entamés sur le sujet : 
- sur l'onglet de écran "Mes effectifs"  : bouton "ajouter un apprenant"
- au clic, ouverture d'une ligne d'effectifs vide à remplir directement en saisissant les éléments dans l'IHM
- un bouton "soumettre" permet d'importer la ou les nouvelles données ajoutées dans les effectifs de l'établissement
- la démarche est historisée dans l'historique des imports de données

**Comment by svengau** [comment]
@nadinelouchart @svengau, c toujours d'actualité ?

**Comment by nadinelouchart** [comment]
Je pense qu'il faut le prévoir si ce n'est pas fait à reboucler avec @ClemLan import des effectifs

**Comment by ClemLan** [comment]
Suite à notre point de la semaine dernière, je croyais qu'on ne la faisait plus : trop de temps de dev pour peu d'usage ? (+ favoriser le téléchargement par fichier)
@nadinelouchart @svengau

**Comment by nadinelouchart** [comment]
Oui on est bien d'accord - mais je n'étais plus sur de ce que l'on s'était dit - je clos la carte du coup @svengau
