### ISSUE TITLE
API V3 : nouvelles données à collecter

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2360]
**Origine du besoin**
Mieux retracer le parcours de l'apprenant et exposer des indicateurs plus fins et plus fiables

**To DO**

- [ ] Atelier metier x tech

- [ ] Faire évoluer l'API afin de collecter plus de champs (pour info, disponibilité de la donnée déclarée par les ERP [dans ce document] (https://docs.google.com/spreadsheets/d/1ngwMf4LDcnjfbCdR6ksXN2PoGB5bXune/edit#gid=408816430))
Liste des champs à collecter ou à auto-compléter (voir specs onglet 3 pour chacune des variables) dans ce document https://docs.google.com/spreadsheets/d/18Tx8KlqH-fBraguBKYnvi4exxKqGabSf-SqrGZfkrgI/edit#gid=0

- [ ] Sécuriser les flux de transfert de données (rgpd)

- [ ] Construire la doc et les accès à la documentation API (url postman)

Quand cette carte est terminée, prévoir les suivantes : 

- [ ]  communication à réaliser auprès des ERP pour mise à dispo de la nouvelle version d'API
- [ ] installer les nouveaux indicateurs (ui + tech) : spec dans [ce document ](https://whimsical.com/macro-roadmap-KzVfv2kyisRLqZNWjQrMzP), partie "parcours apprenant", vdef
- [ ] ajuster la documentation (FAQ sur les indicateurs)
- [ ] ajuster le registre de traitement des données si nécessaire

**Comment by svengau** [comment]
pour ref https://docs.google.com/spreadsheets/d/13HJk630xVY375Bh0TY-rQcz440IrBYQTMmCIZx9xl5g/edit#gid=321987123
