### ISSUE TITLE
[MEP du 16/01] Bouton flottant d'aide présent sur tous les écrans

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2377]
Un bouton flottant d'aide est présent sur tous les écrans du tdb, en bas à droite.
Au clic, j'accède à la page publique Documentation qui est en lecture seule (sans accès en écriture et aux commentaires) : https://www.notion.so/mission-apprentissage/Documentation-dbb1eddc954441eaa0ba7f5c6404bdc0

@cathbaiona => pour lien vers maquette et composant button

**Comment by cathbaiona** [comment]
@pabloHry https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=7131%3A201325&t=8ETlQihh5GS2GUOJ-1
