### ISSUE TITLE
Fixer le passage de l'organisme_id en filtre sur la route indicateurs

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2379]

**Comment by svengau** [comment]
@totakoko, tu es le dernier à avoir travaillé sur cette partie. Toujours d'actualité ?

**Comment by totakoko** [comment]
Je pense que c'était lié au organisme_id qui était rendu quasi-obligatoire par le permissionsOrganismeMiddleware, mais il n'est plus utilisé pour les routes des indicateurs.
