### ISSUE TITLE
Mes effectifs : ajouter un nouvel apprenant (manuel)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2387]
Aujourd'hui : obligation pour les CFA sans ERP de téléverser leur fichier ou de télécharger notre modèle>remplir le modèle>téléverser le modèle

Souhaité : pour les CFA qui accueillent un faible volume d'apprentis, pouvoir alimenter les effectifs directement dans l'interface du tableau "mes effectifs"

**To do**

Dans le parcours, distinguer le fait de télécharger notre modèle vs ajouter manuellement un nouvel apprenant. 
Ajout d'un bouton "ajouter un nouvel apprenant" (attention Ux : éviter la confusion entre l'import d'effectifs via fichier et la saisie manuelle permise par ce bouton)
Au clic, une ligne Apprenant s'ouvre, avec les champs à saisir (année scolaire, nom, prénom, cfd ou rncp, + autres champs visibles dans le toggle).
Les contrôles de format et cohérences sont actifs pour chaque champ de donnée concerné + l'autocomplétion est installée (ex : je saisis le siret, les champs adresse, naf, type etc. sont auto-complétés).
Les messages d'erreur ou d'info manquante sont actifs.
Le bouton d'import permet d'alimenter l'indicateur concerné selon le statut saisi.

**Comment by ClemLan** [comment]
@Anne-Camille On est sûrs que c'est possible au final ? Il me semble qu'à un moment c'était mis de côté

**Comment by Anne-Camille** [comment]
@ClemLan là on l'a mis de côté, mais l'idée c'est de pouvoir le remettre. Par contre la carte est actuellement en Backlog donc ce n'est pas à faire pour tout de suite et pas impossible que ça glisse sur un sprint ultérieur !
