### ISSUE TITLE
Revoir la navigation lors de la creation de compte (bouton revenir)

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2413]
Le bouton revenir présent sur la page post-choix de profil ne permet pas de corriger sur l'écran précédent.

En particulier les boutons pour revenir à l'état précédent qui en fait reviennent au debut du process d'inscription:

![Image](https://user-images.githubusercontent.com/966303/213398523-a0b634e9-4166-41eb-8779-2e742b13f584.png)

**Comment by Anne-Camille** [comment]
ok re7
