### ISSUE TITLE
Un utilisateur non confirmé ne peut plus naviguer sur le site

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2414]
Il voit la page suivante, et impossible d'afficher autre chose

![Image](https://user-images.githubusercontent.com/966303/213398114-7ce023ea-daaa-475c-bf39-697954a67143.png)

**To do**

Installer l'écran suivant : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A289071&t=p65ciwNkoWp9i7BH-1

**Comment by Anne-Camille** [comment]
@cathbaiona @ClemLan : à votre avis, dans cette situation ou l'accès lui a été refusé par l'admin, doit-on 
a. le renvoyer sur la page d'accueil directement
b. lui proposer un écran spécifique "votre demande d'accès a été refusée, vous pouvez contacter le support / votre organisme gestionnaire / retourner à l'accueil pour consulter les indicateurs nationaux"
c. une autre proposition
d. la réponse d

**Comment by cathbaiona** [comment]
Question @Anne-Camille : nous sommes dans la situation où un utilisateur attend sa confirmation de compte par email n'est-ce pas ?
Je prépare un écran plus parlant avec lien de redirection vers la page d'accueil.
Pour la situation où son compte est refusé par le gestionnaire (ou nous, admin) : il l'apprend via un email, il me semble ?

**Comment by cathbaiona** [comment]
@svengau En regardant Figma, j'avais conçu cet écran : 
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A289071&t=p65ciwNkoWp9i7BH-1

**Comment by Anne-Camille** [comment]
@cathbaiona oui, j'ai édité mon commentaire, c'est bien la situation ou la demande est en cours de traitement par l'admin et donc l'écran déjà maquetté est parfait !

**Comment by antoinebigard** [comment]
Le lien figma ne fonctionne plus. d'ailleurs, est-ce prioritaire ?
