### ISSUE TITLE
Terminer le flow de refus de demande d'accès

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2417]
A terminer : 

- à l'invalidation d'accès par l'admin, un email au demandeur l'informe que sa demande d'accès a été refusée.
- à l'invalidation d'accès par l'admin, le demandeur qui retourne sur auth/finalisation est informé que sa demande d'accès a été refusée.

**To do**

- [x] rédiger template de mail
- [x] maquetter page d'accès refusé
- [ ] quand la carte est terminée, réaliser un atelier dev avec le recueil des specs techniques (mail poubelle)
- [ ] quand atelier fait, rédiger la carte tech/dev avec le lien maquette + specs techniques et la mettre en backlog prio

**Comment by cathbaiona** [comment]
Maquettes du parcours ici : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A288025&t=InS0uAyztLuQvl9p-1

**Comment by nadinelouchart** [comment]
@sven 

Modalité de refus - 
Dans le cas ou le gestionnaire refuse un collaborateur : 
=> ouverture d'une fenêtre pour confirmer le refus sans avoir à donner la raison
=> modale - refuser la demande

=> envoi e-mail à la personne refusé => avec e-mail du **gestionnaire responsable** 
est-il possible de créer un e-mail générique a la place de l'email du gestionnaire refusant l'accès pour protéger l'anonymat en cas d'action frauduleuse.

**Comment by nadinelouchart** [comment]
Modalités de refus

=> message a simplifier 

![Image](https://user-images.githubusercontent.com/121936073/222202955-354f825f-6308-41ca-88d9-2dd4af7a7175.png)



![Image](https://user-images.githubusercontent.com/121936073/222203107-acdad8e1-5e5b-4ecc-b039-135a22647441.png)
