### ISSUE TITLE
Upload de fichier : message invitant à patienter pendant les traitements de fichiers

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2420]
Le traitement du fichier post-mapping de colonnes peut être très long selon la taille du fichier et le nbre de colonnes à mapper. Au clic sur "prévisualiser", arrivée sur un écran presque vide avec un spinner.

![Image](https://user-images.githubusercontent.com/63646363/213461105-0757c787-f279-4a9e-804f-5bbfb378627c.png)

Souhaité : renforcer le message qui invite l'utilisateur à patienter.
Exemple de phrase à ajouter : "votre fichier est en cours de traitement, cette opération peut prendre quelques secondes à plusieurs minutes selon la taille du fichier"

**To do**

- [x] maquette de l'écran

**Comment by ClemLan** [comment]
Proposition : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9812%3A296557&t=KBWxEsBoOmkTGjTj-1

**Comment by Anne-Camille** [comment]
caete dev : https://github.com/mission-apprentissage/flux-retour-cfas/issues/2701
