### ISSUE TITLE
Reliquats wording/orthographe/coquilles à corriger

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2421]
- [x] https://cfas-recette.apprentissage.beta.gouv.fr/mon-espace/mon-organisme/effectifs
état de la données => état de la donnée

![Image](https://user-images.githubusercontent.com/63646363/213462672-a01470e0-a913-4234-979c-dcd41928311e.png)

- [x] lien footer "Documentation", remplacer par "A propos".

**Comment by cathbaiona** [comment]
Toutes les coquilles relevées sont ici pour Sven : https://www.figma.com/file/8VanH5KNXBaVHYub9c5bte/Recette?node-id=98%3A2884&t=I46dmvwQCeKEl5DZ-1

**Comment by svengau** [comment]
toutes les coquilles sont normalement fixées, voici la derniere PR: https://github.com/mission-apprentissage/flux-retour-cfas/pull/2596

**Comment by Anne-Camille** [comment]
re7 ok
