### ISSUE TITLE
Revue des parcours inscription/connexion

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2422]
- [x] orga atelier revue du flow d'inscription : objectif = revoir les flow d'inscirption et lister les écarts pour pouvoir les backloger et prioriser. Atelier prévu le 20/02 (45mn)

Notamment : 
- [x] Inscription opérateur public et réseaux : remplacer l'étape 1 de la proposition de siret par directement l'étape 2 de choix du territoire ou de l'académie ou du réseau

Actuellement, quand je sélectionne un profil :
- dreets ou ddets, je m'inscris avec le siret, puis je choisis ma région => souhaité : ne pas passer par l'étape siret mais directement par l'étape choix de région
- académie, je minscris avec le siret, puis je choisis l'académie => souhaité : ne pas passer par l'étape siret mais directement par l'étape choix d'académie
-  "réseau d'of", je m'inscris avec le siret, puis je choisis le réseau dans une selectbox => souhaité : ne pas passer par l'étape siret mais directement par l'étape sélectbox

- [x] revoir le front du choix des régions/dpartement pour les opérateurs publics

- [ ] permettre la validation admin par les gestionnaires de l'OF pour tout nouveau compte créé pour cet OF

**Comment by cathbaiona** [comment]
Ici, les maquettes initialement réalisées (pas de SIRET demandé) et que je vais retravailler pour Réseaux et Académies : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A292353&t=MF5qF4Up86BHGrzy-1
