### ISSUE TITLE
Mail de validation Admin : ajouter en clair le libellé de la région

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2430]
Actuellement, l'email que reçoit l'Admin présente le code région (ex : 52)
Attendu : l'email que reçoit l'Admin affiche le nom de la région en clair (ex : 52 - Pays de la Loire)

Objectif : sécurité = permet de valider les demandes d'accès en comparant les éléments de la demande avec le périmètre sur lequel doit pouvoir intervenir le demandeur

Si besoin, ajout de la nomenclature : 
01 - Guadeloupe

- 977 - St Barthélémy
- 978 - St Martin

02 - Martinique

03 - Guyane

04 - La Réunion

06 - Mayotte

11 - Ile de France

24 - Centre Val de Loire

27 - Bourgogne Franche Comté

28 - Normandie

32 - Hauts de France

44 - Grand Est

52 - Pays de la Loire

53 - Bretagne

75 - Nouvelle Aquitaine

76 - Occitanie

84 - Auvergne Rhône Alpes

93 - Provence Alpes Côte d’Azur

94 - Corse

**Comment by svengau** [comment]
https://github.com/mission-apprentissage/flux-retour-cfas/pull/2575

**Comment by Anne-Camille** [comment]
@svengau je ne vois pas le libellé de région en recette (je copie colle le mail Admin reçu en recette et en rose, ce que je devais voir) : 



![Image](https://user-images.githubusercontent.com/63646363/218785755-bf1d0e1a-aa5b-4f2f-9e17-cd6b72e9ea2e.png)

**Comment by svengau** [comment]
il y a eu un malentendu, j'avais compris que c'etait l'email de demande d'acces qu'il fallait mettre a jour
cf screenshot sur la PR: https://github.com/mission-apprentissage/flux-retour-cfas/pull/2575

**Comment by svengau** [comment]
nouvelle PR https://github.com/mission-apprentissage/flux-retour-cfas/pull/2597

**Comment by Anne-Camille** [comment]
re7 ok
