### ISSUE TITLE
[Fiabilisation]

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2436]
Sujet Fiabilisation des données : 

- [x] #2532
- [x] #2534
- [x] #2547
- [x] #2548
- [x] #2549
- [ ] #2550
- [x] #2551
- [x] #2552
- [ ] #2553
- [ ] #2554

-------------------------------------------------------------------------------------------------------------------------------------

Aujourd'hui : certains scripts ne passent pas correctement ou pas dans le bon ordre.

Nous affichons les siret fermés ou des établissements avec des fake UAI (ex : 0000001N) :
1. il faut vérifier que les scripts de fiab remplacent bien les données fake ou inactives par des bonnes données et que les effectifs correspondants sont bien importés
2. afin de pouvoir détecter les établissements en erreur et non corrigeables=> nous devrions stocker ces retours d'erreurs pour pouvoir indiquer en front "les effectifs de ces établissements n'ont pas pu être importés + motif afin de permettre aux établissements de corriger à la source et par la suite, concevoir un flux retour automatisé vers les ERP.

**Comment by sbenfares** [comment]
Je ferme la carte "Macro" fiab vu qu'on a toutes les cartes définies unitairement plus besoin de celle ci
