### ISSUE TITLE
Admin : Page gestion des utilisateurs : modifs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2455]
- [x] Pour un compte pilote : préciser le périmètre territorial d'accès demandé

- [x] Retirer les infos relatives à chaque organisme du périmètre pour ne permettre qu'une confirmation totale d'accès : voir https://github.com/mission-apprentissage/flux-retour-cfas/issues/2706

- [x] Remplacer le wording des labels : 

    - NOT_CONFIRMED => L’utilisateur s’est inscrit, mais n’a pas validé sa demande dans l’email qu’il a reçu, on ne peut rien faire tant qu’il n’a pas fait cette démarche. Ce label devrait être remplacé par  "en attente de validation utilisateur"
    - FIRST_FORCE_RESET_PASSWORD =>L’utilisateur a validé sa création de compte depuis l’email qu’il a reçu, il est invité à créer son mdp. On ne peut tjs rien faire en tant qu’admin. Ce label devrait être remplacé par "création mdp en cours"
    - FORCE_COMPLETE_PROFILE_STEP1 => L’utilisateur a créé son mdp, un mail “admin” de validation d’accès a été envoyé dans notre bal ou dans la bal , nous pouvons valider ou refuser selon analyse. Ce label devrait être remplacé par "à valider administrateur"
    - FORCE_COMPLETE_PROFILE_STEP2 => l’accès a été validé par un admin ; l’utilisateur a reçu un mail l’en informant mais il n’a pas encore cliqué sur le bouton "accéder à mon espace". Ce label devrait être remplacé par "accès ouvert - en attente de 1ère utilisation"
    - CONFIRMED => "accès confirmé" ; l’utilisateur a accédé à son espace
    - FORCE_RESET_PASSWORD ⇒ défini pour des comptes de développement et contourner le processus de validation classique. Après avoir défini son mdp, l’utilisateur passe en **CONFIRMED** directement.

**Comment by cathbaiona** [comment]
Début de maquettes : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9729%3A283683&t=UEWLWWeVpzOm6GRP-1

**Comment by Anne-Camille** [comment]
re7 ok
