### ISSUE TITLE
Régression : Rétablir la fonctionnalité d'export de liste anonymisées pour les opérateurs publics

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2459]
Mail reçu par une DRAAF : La fonctionnalité d'export des données pour le Grand Est m'était très utile. En effet, avec le tableur Excel, je pouvais identifier les apprenants préparant un diplôme du Ministère de l'Agriculture (Chiffre en 3 en troisième position du code diplôme à 8 chiffres)

- [x] vérifier la régression (cf DREETS parviennent bien à télécharger le rapport)
- [x] analyser l'opportunité de proposer une vue draaf avec les données déjà filtrées sur le 3e chiffres du cfd) : si pertinent, carte ux-atelier à créer => fait, https://github.com/mission-apprentissage/flux-retour-cfas/issues/2530

**To do**

Quand je suis un opérateur public, sur la partie Mon tableau de bord, je dispose d'un lien "Télécharger" : le fichier de sortie est la liste des effectifs anonymisée sur mon territoire.

![Image](https://user-images.githubusercontent.com/63646363/217823851-3d56fabe-3405-4be0-b7f6-68f1db7e6379.png)

**Comment by totakoko** [comment]
Tout à fait :)

**Comment by Anne-Camille** [comment]
re7 ok
