### ISSUE TITLE
Contacter ERP (acquisition données)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2466]
- [ ] Lister les ERP déjà demandeurs (voir ERP en attente : liste sur HP tdb + contacts BAL)
- [ ] Contacter les ERP déjà contactés pour le SI des OPCO (liste page 12 de [ce document](https://docs.google.com/presentation/d/1Y4U6cyxQwtRNWvoSoOkZZ-RcUmJ_NvSG/edit#slide=id.p17))

A chaque contact d'un nouvel ERP, demander le volume potentiel d'apprentis et transmettre la doc API le cas échéant.

Dans instruction SIFA : 

![Image](https://user-images.githubusercontent.com/63646363/218517677-abdd8d27-8c42-476d-880d-fc1ad75662c9.png)

Pour mémoire, dans le doc OPCO, sont déjà branchés : 
YPAREO 
SC-FORM
UNIVERSITE DE LORRAINE
FORMASUP IDF,  HDF,  ARL
IMCI
UNIVERSITE DE PARIS
ES BANQUE
FILIZ
ECOLE 2600
GROUPE GEMA
AMMON
AIMAIRA 
IONIS Education Group
PRESTIM 

A venir : 
FCA Manager	
GESTIBASE
GALILEO GLOBAL EDUCATION  
CESI 
EPITECH 
ILABS
CFA ESPL
ICADEMI	
AURIGA
FORMAWAY
…

**Comment by nadinelouchart** [comment]
a traiter  avec la carte https://github.com/mission-apprentissage/flux-retour-cfas/issues/2911
pour complements eventuels
