### ISSUE TITLE
Permettre à un OFR ou OFRF de faire un seul upload pour tous ses établissements formateur

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2467]
Aujourd'hui : 
Un OF responsable (OFR) ou un OF responsable-formateur (OFRF) doit se rendre sur chaque enfant pour uploader les effectifs de chacun d'entre eux

Souhaité : 
Un OFR ou OFRF peut uploader un seul et même fichier pour les effectifs de tous les établissements rattachés (et lui-même s'il est OFRF).

**To do**

- [ ] avérer le besoin (ux research) auprès d'OFR et OFRF => à ce jour, une seule remontée (Kedge)
vérifier les pratiques (je déclare pour moi-même seulement / je déclare pour moi-même+ tous les autres en même temps / je déclare pour moi-même puis pour tous les autres dans un second temps...)

- [ ] si besoin avéré et pratique définies, prévoir le cas échéant des parcours différents pour permettre aux OFR et OFRF de déclarer pour leurs enfants (veiller à  intégrer la demande de colonne UAI ou SIRET dans le fichier comme donnée obligatoire pour pouvoir répartir les effectifs entre les différents établissements).

**Comment by cathbaiona** [comment]
Contacter sarah.poussielgue@btpcfa-pdl.com
CFA BTP PDL
1700 apprentis - 2 centres de formation

Autre contact : 
CFA Agricole du Lot et Garonne 0470815F (gestionnaire et formateur) sur Ypareo
(suite entretien UFA : Ingrid Ebzant, Agro Bordeaux)
