### ISSUE TITLE
Traduire en français les messages d'erreur actuellement en anglais

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2469]
Concerne essentiellement les toaster.
Exemples de messages EN vus sur "Mes effectifs"  : 
- suppression de fichier
- erreur de chargement (taille)

**To Do**

- [ ] si possible, extraire une liste des messages d'erreur actuellement codés =>dev
- [ ] traduire les messages et corriger dans le code

**Comment by nadinelouchart** [comment]
@sven ou en est-on sur cette carte ?

**Comment by svengau** [comment]
je viens de pusher une PR https://github.com/mission-apprentissage/flux-retour-cfas/pull/2921
