### ISSUE TITLE
Admin : gestion des utilisateurs : ajouter un moteur de recherche

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2471]
Sur la page admin/gestion des utilisateurs : avoir un moteur de recherche permettant des recherches par UAI, siret, raison sociale (OF, dreets, deets,...), adresse email, nom, prénom

Reste à faire : 

- [x] créer les cartes dev reliquats non pris en charge (autre que moteur de recherche) puis clôturer en terminé : https://github.com/mission-apprentissage/flux-retour-cfas/issues/2877

**Comment by cathbaiona** [comment]
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9729%3A283683&t=UEWLWWeVpzOm6GRP-1
