### ISSUE TITLE
dans téléversement, ajouter un lien pour revenir sur la configuration de l'ERP

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2476]
demande de Catherine: Peut-on rajouter un moyen de rebasculer vers la solution “ERP” (et funnel) ?

![Image](https://user-images.githubusercontent.com/966303/215447556-06b95d92-18b2-460c-9c26-c5843fb9331f.png)

cf https://www.figma.com/file/8VanH5KNXBaVHYub9c5bte/Recette?node-id=33%3A787&t=BjbNRTiMWK7k50vF-4

**Comment by Anne-Camille** [comment]
cf travail en cours sur le parcours utilisateur par @ClemLan

**Comment by ClemLan** [comment]
Fait partie du travail effectué avec @Anne-Camille le 02/02. Pour review : [➡️ lien whimsical ]((https://whimsical.com/effectifs-Q37nAjMXNkMHUhbovqfnw7))

**Comment by ClemLan** [comment]
Tous les parcours de/vers ERP sont sur : [cette page Figma](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9669%3A283886&t=KBWxEsBoOmkTGjTj-1)
