### ISSUE TITLE
Admin : impossible de créer un utilisateur / erreur 409

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2491]
En tant qu'admin, je veux créer un nouvel utilisateur.

Au clic sur enregistrer, toaster erreur 409

![Image](https://user-images.githubusercontent.com/63646363/215766513-0000bdca-ddc0-4a91-9203-c55a1acc2dd2.png)

**Comment by svengau** [comment]
https://github.com/mission-apprentissage/flux-retour-cfas/pull/2574

**Comment by Anne-Camille** [comment]
@svengau nok en recette : 

![Image](https://user-images.githubusercontent.com/63646363/218787295-3f2c1277-c70b-45a4-88bc-e57c290b770a.png)



![Image](https://user-images.githubusercontent.com/63646363/218787419-61a7c23b-df01-45d7-891f-03975c1c078c.png)

**Comment by svengau** [comment]
L'email test@test.recette n'est pas valide, et la gestion des erreurs n'est pas ideal. Je viens de tester avec un email valide, ca marche bien, et le formulaire est bien réinitialisé, pour éviter à l'utilisateur de re-creer un meme compte (et d'avoir une erreur 409)

**Comment by Anne-Camille** [comment]
suite échange, recette sur l'erreur 409 ok, autre carte tenant compte de l'autre message vu en recette créée en backlog (https://github.com/mission-apprentissage/flux-retour-cfas/issues/2593)

**Comment by Anne-Camille** [comment]
re7 ok
