### ISSUE TITLE
Import de fichier en erreur (fichier invalide)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2492]
Plusieurs types de fichiers maisons ne passent pas la barrière de l'import (fichier invalide) en conditions utilisateurs : 

- kedge : import KO chez eux, OK chez nous en recette mais spinner infini entre l'étape de nommage du fichier et l'étape de mapping

- yschool : import KO chez eux, OK chez nous en recette

- Filea : import KO chez eux, OK chez nous en recette (mais étape d'import qui n'a pas abouti cependant)

![Image](https://user-images.githubusercontent.com/108516993/215795226-f71f0356-e92f-418b-a815-eb04664a5436.png)

**Comment by svengau** [comment]
j'ai testé 2 cas:
- `fichier_test_Kedge.xlsx`: apres l'avoir converti en CSV, l'import se passe bien, par contre c rapide en local, mais 22 minutes(!!) en recette
- `EXEMPLEY SCHOOLS sans modif.csv`: OK en recette.

Du coup, il faudrait avoir plus d'informations de la part des clients, avec eventuellement des screenshots d'écran.
