### ISSUE TITLE
Création d'utilisateur admin sans accès aux organismes

### ISSUE THREAD

**Issue by totakoko** [mission-apprentissage/flux-retour-cfas#2498]
Un utilisateur admin nouvellement créé n'a pas le droit d'accéder à tous les organismes. Or ça devrait être le cas.

**Comment by nadinelouchart** [comment]
Est-ce que cela a été fait ? comment verifier ? @totakoko @svengau

**Comment by totakoko** [comment]
Corrigé avec le nouveau système de permissions. On peut juste vérifier qu'en tant qu'admin. On peut aller sur n'importe quelle page d'organismes, sans erreur.
