### ISSUE TITLE
Fiabilisation Réseaux - Lien entre TDB & Référentiel

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2509]
Vérifier que PR 2306 permet de remonter le réseau AFTRAL dans le référentiel
Et vérif autres réseaux : a priori ok TDB et nok référentiel 

- [x] Corriger l'import du stock des organismes référentiel dans le tdb
- [x] Corriger le séquencement des scripts coté infra
- [x] Corriger l'import du tdb dans le référentiel
- [x] Corriger les doublons de réseau code cfa ec -> cfa_ec via un script d'update

**Comment by sbenfares** [comment]
Première analyse du 09/02/2023 : Coté référentiel le script quotidien de build ne va pas jusqu'au bout.
Echange prévu avec GA de l'onisep pour voir comment solutionner ça.

**Comment by sbenfares** [comment]
Fix & PR faites sur le référentiel + déploiement fait hier soir (09/02/2023)

**Comment by sbenfares** [comment]
PR de nettoyage des réseaux faite coté référentiel, en attente déploiement / merge par GA

**Comment by nadinelouchart** [comment]
OF redacteur - bug de telechargement sur un fichier vide ?


![Image](https://user-images.githubusercontent.com/121936073/218122950-c75cca9f-b567-4992-b9c3-f587d6fbd4b1.png)

**Comment by sbenfares** [comment]
@nadinelouchart @totakoko (Maxime) est en train de travailler à un fix sur l'import (cf. https://github.com/mission-apprentissage/flux-retour-cfas/pull/2563) c'est peut être lié ?

Coté réseaux il n'y a pas de lien en tout cas normalement.

**Comment by sbenfares** [comment]
Suite à remontée d'anomalie par @Anne-Becquet on a identifié des organismes dont on ne remonte qu'un couple UAI-SIRET depuis le référentiel dans le Tdb (ex: UAI 0142321X et 0611309S).

Il faut corriger le script hydrate-organismes pour remonter tous les couples UAI-SIRET

**Comment by sbenfares** [comment]
En attente review & deploy
