### ISSUE TITLE
Demander l'autorisation pour consommer l'API Entreprise

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2510]
Suite demande de renouvellement token => demander un token TDB
Contacts : toutes les adresses suivantes sont en @ insee . fr 
gerard.vittek
dominique.tallec-santoni
gilles.scazzola

edit suite retour email => https://entreprise.api.gouv.fr/ et https://api.insee.fr/catalogue/

procédure de demande : 
https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/help.jag#commencer

boite fonctionnelle de contact si besoin : DG75-SIRENEGC   en @ insee.   fr

**Comment by svengau** [comment]
comme discuté, la mission a déja un compte api entreprise => on archive
