### ISSUE TITLE
Régression : Contacter RCO pour redéfinir les besoins suite coupure de l'accès aux données anonymisées

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2513]
Avant : avaient accès via API aux effectifs anonymisés
Maintenant : API coupée
Demain : rétablir les accès après avoir réinterrogé les besoins

**Comment by cathbaiona** [comment]
Réponse de M. Billion , Responsable du domaine Observation et information sur l’Offre de formation

Utilisait déjà le Tableau de bord, appréciait l’accès aux données assez fines.

Réunion prévue le 28 février avec les services de l’Etat et de la Région est destinée à faire le point sur la situation des apprentis sans contrat, CFA par CFA.
Pour cette 1ère réunion, le manque d’informations adaptées n’est pas rédhibitoire car c’est l’enclenchement d’une démarche. En revanche, par la suite nous aurons besoin d’avoir des informations beaucoup plus fines par niveau, certification…


Nous sommes une structure ressource pour l’État et la Région, notre Besoin doit être le plus fin possible : à la fois en termes d’effectifs par CFA, par certification, et par situation d’apprenti (rupturants, abandons…).

Au pire, les listes nominatives, « on en n’a pas forcément besoin. ce n’est pas indispensable, loin s’en faut, ce n’est pas cela qui me préoccupe le plus. »
On peut effectuer un travail avec un CFA que nous avons identifié en difficulté. Il peut nous retrouver les apprentis de son côté.

Par contre, on a besoin de savoir que dans tel CFA, il y a X apprentis en difficulté parce qu’il est, en abandons, en rupture, etc… ça c’est important pour nous.

**Comment by Anne-Camille** [comment]
OK, décision : pas de création de compte native RCO + pas de vue spécifique RCO (idem vue régionale/DREETS) => ce sont les DREETS qui inviteront.
A date, on ne créé/valide de compte RCO qu'après accord de la DREETS pour leur donner accès.
