### ISSUE TITLE
Suppression table siret-UAI native tdb

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2515]
En priorité, supprimer la table siret-uai

**Comment by Anne-Camille** [comment]
@sbenfares celle-ci est terminée il me semble ? merci !

**Comment by sbenfares** [comment]
> @sbenfares celle-ci est terminée il me semble ? merci !

Alors je ne sais pas vraiment à quoi elle correspond, mais je pense qu'elle fait doublon avec une de mes cartes.
Donc tu peux la close 🙏🏼 merci
