### ISSUE TITLE
Mailing LBA inscrits sans contrat

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2521]
Objectif : permettre à lba de mieux cibler les mailing auprès des sans contrat. 1ère campagne LBA prévue : mailing voeux Affelnet courant mai.

- [x] Récupérer la clé ministère depuis le catalogue pour chaque apprenant

To do : 

- [ ] dans le catalogue, récupérer la clé ministère éducatif (elle comporte des indicatif de la session de formation + le lieu de formation)=>  l'adosser à la collection mes organismes ? => dev

Une nouvelle carte sera créée pour le reste : 

- [ ] Industrialiser la requête : extrait des apprenants inscrits sans contrat depuis + de 31 j (requêtable à tout moment pour campagnes de mailing) => data analyse

- [ ] capitaliser les retours de jeunes qui expriment qu'ils ne sont plus sans contrat et transmettre les éléments à l'OF concerné pour maj de ses bases => spec metier

- [ ] mettre en visibilité sur le tdb comme "donnée en erreur" les données email en hardbounce suite à campagne LBA (APisable par équipe LBA) )

Doc retex : https://docs.google.com/document/d/1j-ZdE0nvlnfROjfXdYqoemq59id0KbyxGV4OFkDpRtc/edit

**Comment by svengau** [comment]
du coup pour résumer:
- pour chaque formation, sauver la clé ministère éducatif du catalogue dans notre base, et l'exposer dans notre API.

**Comment by totakoko** [comment]
Standby car gestion des formations pas claire cf #2734

**Comment by svengau** [comment]
@nadinelouchart @Anne-Camille, vous pouvez clarifier svp ?
