### ISSUE TITLE
"Inviter un collaborateur" ne fonctionne pas

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2524]
Je suis un organisme gestionnaire, j'accède à mes paramètres, je souhaite inviter un collaborateur.
Je renseigne son courriel et je clique sur le CTA "inviter" => Application error: a client-side exception has occurred (see the browser console for more information).

![Image](https://user-images.githubusercontent.com/63646363/217557239-8949eccf-f20b-4280-a8e0-5809af0ce464.png)

**Comment by nadinelouchart** [comment]
Lors de l'inscription d'un collaborateur - message d'erreur suivant "en anglais" :(



![Image](https://user-images.githubusercontent.com/121936073/218444943-b4d1cd26-7298-479c-a10a-4d6da3b1a6eb.png)

avec blocage du site et aucune possibilité de revenir en arrière

si retour en arrière une fois fait - bug sur le bouton paramètre qui te redirige sur la page erreur.

tentative de connexion et reconnexion et a nouveau le bouton paramètre dirige vers le message d'erreur.

**Comment by svengau** [comment]
dupliqué avec https://github.com/mission-apprentissage/flux-retour-cfas/issues/2334
