### ISSUE TITLE
Permettre à un opérateur public de voir quels sont les contacts d'un OF

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2536]
![Image](https://user-images.githubusercontent.com/63646363/217848908-6d3f2842-c443-4ff4-9564-c60075c2379e.png)

Lorsque je suis un opérateur public, j'accède au tableau de bord d'un organisme de formation, sur cet écran, je peux voir qui sont les contacts (adresses emails des personnes qui ont créé un compte sur le tdb pour cet of ) ; objectif : en cas d'écarts ou si je veux mener des campagnes auprès des jeunes en rupture/non inscrits/abandons, je peux contacter l'OF en amont.

- [ ] interroger les OF connectés 
- plusieurs pistes possibles pour mettre à dispo des opérateurs publics  une coordonnée de contact : 
1. permettre à l'of de renseigner un email pour les contact avec les dreets
2. permettre à l'of de refuser que son mail soit visible des of (opt-out)

**Comment by cathbaiona** [comment]
Pour que le contact d'un organisme apparaisse dans ce bandeau
<img width="827" alt="Capture d’écran 2023-03-02 à 14 53 25" src="https://user-images.githubusercontent.com/108516993/222447853-b747c621-f9ed-48c8-bcb6-e165beb9e3de.png">
2 possibilités envisagées : 

- [ ] à la création d'un compte OF, la personne a le choix (avec une case à cocher) de faire apparaître son email
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A288459&t=ewgqoZpvdWmLQbVv-1
<img width="507" alt="Capture d’écran 2023-03-02 à 14 54 45" src="https://user-images.githubusercontent.com/108516993/222448772-3bf1e6bb-d278-4a89-b590-3544af52e6d1.png">

- [ ] Dans les paramètres de son Compte, dans l'onglet "Informations", on retrouve la case à cocher pour accepter d'être contacté par un OP
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A291116&t=ewgqoZpvdWmLQbVv-1
<img width="757" alt="Capture d’écran 2023-03-02 à 14 58 25" src="https://user-images.githubusercontent.com/108516993/222449277-c7b87572-1fd0-4c5b-aef6-3eeb2297c869.png">
