### ISSUE TITLE
Revue du parcours d'import / complétion d'effectifs / corrections d'effectifs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2537]
- [x] travail préliminaire : https://whimsical.com/effectifs-Q37nAjMXNkMHUhbovqfnw7
- [x] 1er draft maquettes (carte liée https://github.com/mission-apprentissage/flux-retour-cfas/issues/2387)
- [x] consultation dev /ajustements éventuels maquettes
- [ ] test maquettes utilisateurs

**CAS 1**
Parcours d'import pour un OF non transmetteur , 1er cas, avec [le template tdb](https://docs.google.com/spreadsheets/d/1KI-Hq9viDZ9D6ZJD-SGrvOqX9eD37Rp5/edit#gid=953740490)

**CAS 2**
Parcours d'import pour un OF non transmetteur, 2e cas, avec son propre fichier.

Les actions de ajout/suppression d'apprenants // AJout/suppression/modification de donnée apprenant, dans cette 1ère étape, passeront par l'upload d'un nouveau fichier.

**Comment by Anne-Camille** [comment]
@ClemLan constaté par Nadine : le message qui apparaît aujourd'hui pour tout le monde en cas de 0 transmission n'est pas adapté pour un OF avec une permission "lecteur" (il faut juste prévoir d'avoir des écrans contextualisés pour un simple lecteur avec un message d'info adapté) 

![Image](https://user-images.githubusercontent.com/63646363/218063203-ff428da5-25a3-4e3f-a12b-7a96f72799a7.png)

**Comment by Anne-Camille** [comment]
@ClemLan je clôture la https://github.com/mission-apprentissage/flux-retour-cfas/issues/2476 car reprise en compte dans le travail de la présente carte

Je remets ici le lien que tu vais mis dans la carte : https://github.com/mission-apprentissage/flux-retour-cfas/issues/2476

**Comment by nadinelouchart** [comment]
Recette revue et corrigée - OK pour passer en prod https://github.com/mission-apprentissage/flux-retour-cfas/issues/2930
