### ISSUE TITLE
Import d'effectifs : modification et simplification du template d'import

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2538]
- [x] modifier et simplifier le template de transmission d'effectifs
- [ ] réduire en conséquence le nombre de colonnes à mapper (dans l'écran mapping, la selectbox concernant la colonne attendue par tdb ne comporte plus que les noms des libellés du nouveau template)

fichier modifié : https://docs.google.com/spreadsheets/d/1KI-Hq9viDZ9D6ZJD-SGrvOqX9eD37Rp5/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true

Les données en orange sont obligatoires 

Carte suivante : calcul des indicateurs en fonction des données nouvellement recueillies =>[ ici](https://github.com/mission-apprentissage/flux-retour-cfas/issues/2707)

**Comment by nadinelouchart** [comment]
@sven est-ce déjà une carte en cours ?

**Comment by svengau** [comment]
Non, mais je peux regarder maintenant si tu veux

**Comment by svengau** [comment]
@nadinelouchart, Pas mal de champs qui sont en fait dans l'api V3, donc je bouge dans la colonne "Running Status"

**Comment by nadinelouchart** [comment]
@svengau parti intégrante de restitution de donnée - nouveau schema de données en lien avec API V3
