### ISSUE TITLE
Rédiger éléments de langage sur le non-Affichage du taux de saturation/ places restantes par formation

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2543]
Besoin remonté suite tests DREETS DDETS => [doc de référence](https://mission-apprentissage.notion.site/2022-02-Restitution-tests-DREETS-DDETS-24093bd92daf400f8d524593eda1c1f4)

Quel est le besoin véritable ? Peut-être que le nouveau schéma de données permettra de répondre au besoin
Pb : donnée peu fiable quand renseignée donc pas trop favorable à exposer cette donnée
L'exposition de l'email du gestionnaire de l'OF permet aux dreets d'entrer en contact et de poser la question au cas par cas

**To do**

- [x] Rédiger des éléments de langage pour expliquer qu'on n'exposera pas cette donnée => avec @Julianne-Lagadec 
- [ ] Alimenter la FAQ Opérateur public avec ces éléments de langage

**Comment by nadinelouchart** [comment]
Proposition de texte : 
**Est-ce que le TdB peux communiquer le nombre de places vacantes au sein des formations CFA ?**
Bien que plébiscité par plusieurs services publics, le partage de cette information est difficilement transcriptibles par les organismes de formation et leurs systèmes d’informations - 
En effet, il est difficile de déterminer le nombre de places vacantes au sein des formations quelques soient ces dernières - issus de service ou de l'industrie
Pour autant il sera possible de communiquer le nombre de places d'une année à l'autre en servant un historique.

**Comment by Anne-Camille** [comment]
Proposition : 

**Pourquoi le tableau de bord n'indique pas le nombre de places vacantes ?**

La loi “Avenir Professionnel” du 5 septembre 2018 permet à toute personne d’entrer en apprentissage et de sortir à tout moment.  Les organismes de formation en apprentissage peuvent donc ouvrir des places tout au long de l'année et chaque apprenti peut suivre son propre itinéraire de formation.
Par conséquent, la donnée "place vacante" n'est pas disponible faute de pouvoir être définie ; il convient de contacter l'organisme de formation pour savoir à quel moment il est possible d'accueillir un nouvel apprenti pour qu'il démarre son parcours de formation.
A cette fin, le tableau de bord de l'apprentissage proposera prochainement des coordonnées de contact au sein de l'organisme de formation (sous réserve de son consentement à les rendre visibles) et à titre indicatif, une information comparative du volume d'apprentis accueillis entre la période N et la période N-1.

**Comment by Anne-Camille** [comment]
@nadinelouchart la carte est réellement terminée (cad on a fait relire à Julianne et alimenté la FAQ) ou alors il reste à faire ces 2 actions ?

**Comment by nadinelouchart** [comment]
Pour moi elle est terminé. Julianne n’avait pas forcement plus d’argument  a apporter. Et ton texte est très bien – je l’ai mis dans la FAQ

Envoyé à partir de Courrier pour Windows

De : Anne-Camille
Envoyé le :vendredi 17 mars 2023 11:40
À : mission-apprentissage/flux-retour-cfas
Cc : nadinelouchart; Mention
Objet :Re: [mission-apprentissage/flux-retour-cfas] Rédiger éléments de langage sur le non-Affichage du taux de saturation/ places restantes par formation (Issue #2543)

@nadinelouchart la carte est réellement terminée (cad on a fait relire à Julianne et alimenté la FAQ) ou alors il reste à faire ces 2 actions ?
