### ISSUE TITLE
Opérateurs publics : Exposer les listes de jeunes ayant réalisé un voeu en apprentissage Affelnet / Parcoursup

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2546]
en lien avec le calendrier des voeux : 

- [ ] Affelnet
- [ ] Parcoursup
- [x] Mon master (=> pas prêt cette année)

1. voir avec Anne pour rex de l'année précédente (atelier avec Clémence)
2. voir de quelle façon intégrer/ industrialiser et rendre les données accessibles et + visuelles sur TDB

fichier json nom-prenom (voir ci-dessous et [ce doc](https://docs.google.com/spreadsheets/d/1zq8TmrUz9lR4HVyqR38ObUBmGqYhCwNgytkBJ5x87j4/edit?usp=sharing))

- affichage du nombre de voeu exprimé selon affelnet ou parcoursup (non nominatif) en + dans les effectifs sur l'organisme

- calcul taux de transformation d'un voeu

- exposer l'indicateur côté dreets : un OF a des voeux et ne transmet pas

- définir la structure d'accompagnement du jeune grâce à l'UAI du CIO d'origine qui peut être intéressante pour mobiliser la structure territoriale compétente si le jeune devient sans contrat (permet d'identifier le territoire).

=> travail fichier en mai pour mise en prod en juin

**Comment by Anne-Camille** [comment]
Académie possédant le dossier élève;INE;Nom de l'élève;Prénom 1;Prénom 2;Prénom 3;Adresse de l'élève - Ligne 1;Adresse de l'élève - Ligne 2;Adresse de l'élève - Ligne 3;Adresse de l'élève - Ligne 4;Code postal;VILLE;PAYS;Téléphone personnel;Téléphone professionnel;Téléphone portable;Téléphone responsable 1;Téléphone responsable 2;Mail responsable 1;Mail responsable 2;Mnémonique MEF origine de l'élève;Code Spécialité du MEF origine de l'élève;Libellé formation origine de l'élève;Code Option 1 d'origine de l'élève;Libellé  Option 1 d'origine de l'élève;Code Option 2 d'origine de l'élève;Libellé Option 2 d'origine de l'élève;Code LV1 d'origine de l'élève;Libellé LV1 origine de l'élève;Code LV2 d'origine de l'élève;Libellé LV2 origine de l'élève;Code UAI étab. origine;Type étab. origine;Libellé étab. origine;Ville étab. origine;Code UAI CIO origine;Libellé CIO origine;Rang du vœu;Code offre de formation (vœu);Code MEF;Avec barème ?;Mnémonique MEF de l'offre de formation;Code spécialité de l'offre de formation;Libellé formation;Code Enseignement Optionnel;Libellé Enseignement Optionnel;Dossier de candidature en internat demandé ?;Code LV1 demandée;Libellé  LV1 demandée;Code LV2 demandée;Libellé LV2 demandée;Code UAI étab. Accueil;Type étab. Accueil;Libellé établissement Accueil;Ville étab. Accueil;SIRET UAI gestionnaire;clé ministère éducatif
Aix-Marseille;090482844BH;PETEL;Quentin;;;;;La Chaussée;;44520;MOISDON-LA-RIVIERE;FRANCE;33632526275;;;;;;;3EULIS;;3EME ULIS;;;;;AGL1;ANGLAIS LV1;ESP2;ESPAGNOL LV2;0840006A;COLLEGE;VIALA;AVIGNON;0840047V;CIO ETAT AVIGNON;6;APP11394;24125434210;Non;1CAP2;25434;1CAP2  REPARATION DES CARROSSERIES;;;Non;AGL1;ANGLAIS LV1;ESP2;ESPAGNOL LV2;0840042P;LP;ROBERT SCHUMAN;AVIGNON CEDEX 2;19840005300023;053381P012X1984000530002319840042600013-84007#L01

**Comment by ClemLan** [comment]
@Anne-Camille est-ce que ça a un lien avec le message d'Anne ? : 
"est ce que tu peux stp contacter Milena [milena.estorniolo@emploi.gouv.fr](mailto:milena.estorniolo@emploi.gouv.fr)  qui va reprendre l'étude quantitative et qualité et la suite de l'enquête de Célia. je lui ai proposé que tu puisses l'aider sur des ateliers ou des entretiens utilisateurs si ça te dit."

**Comment by Anne-Camille** [comment]
- [ ] Exposer le volume de voeux avec  :

- distinction voeux afflenet (dont distinction mineurs/majeurs) / voeux parcoursup /prépa apprentissage /prise de rdv LBA

- national/région/département/OF

- [ ] Exposer le taux de transformation en apprentissage 

- [ ] Exposer le taux de pression sur la formation = identifier le volume de jeunes intéressés par la formation, ce qui permet aux CFA de planifier leur rentrée
