### ISSUE TITLE
Requête d'identification des doublons sur la base du SIREN

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2547]
Script pour sur la base d’un SIREN commun identifier les doublons nom / prénom / date de naissance de l’apprenant. // faire rouler avec script qui vérifier typo

**Comment by felixat13** [comment]
J'ai une première requête, mais certains cas passent encore à la trappe pour des histoires d'accent (le $toLower ne fonctionne pas sur les majuscules avec accent, je vais tester autre chose).
https://cfas-recette.apprentissage.beta.gouv.fr/metabase/question/92-liste-doublons-effectifs
