### ISSUE TITLE
Requêtes d'exposition des données (bucket) en fonction de date de dernière transmission

### ISSUE THREAD

**Issue by sbenfares** [mission-apprentissage/flux-retour-cfas#2549]

**Comment by felixat13** [comment]
Requête MB permettant de filtrer les organismes selon le nombre de semaines écoulées depuis leur dernière date de transmission : https://cfas-recette.apprentissage.beta.gouv.fr/metabase/question/159-liste-organismes-derniere-transmission-x-semaines-filtre-au-choix-dans-la-requete
