### ISSUE TITLE
Sécurité : prévoir une déconnexion automatique d'un compte  loggé

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2568]
Prévoir une déconnexion des comptes - après un temps (entre 8h et 12h)
question comment se passe les mise à jour des base si personnes logués en même temps ?

- [ ] les règles de déconnexion actuelles (compléter dev) => a priori aujourd'hui déconnexion auto 24h après la connexion = à vérifier
- [ ] les règles de déconnexion de demain (spécifier PO) => souhaité : déconnecter chaque soir

**Comment by nadinelouchart** [comment]
Question générale - a quoi sert l'espace "Mon espace" le gestionnaire ou l'utilisateur a-t-il la possibilité de voir d'autre espace que le sien ? si non à quoi sert ce bouton ?

**Comment by svengau** [comment]
@nadinelouchart Le cookie actuel expire au bout de 30 jours. On réduit à 6 jours dans un premier temps ?

**Comment by svengau** [comment]
ping @nadinelouchart

**Comment by nadinelouchart** [comment]
OK POUR MOI
