### ISSUE TITLE
Inviter un collaborateur : label "courriel" à positionner au-dessus du champ de saisie

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2571]
Lorsque je veux inviter une personne  - je dois remplir un champs - a quel moment me demande t on que ce champs soit un e-mail ?
avant d'arriver sur le message suivant ...

![Image](https://user-images.githubusercontent.com/121936073/218444017-12ad34e3-fec4-4066-bbb8-9b8172815855.png)

**Comment by nadinelouchart** [comment]
![Image](https://user-images.githubusercontent.com/121936073/218449517-da343808-673c-4943-9338-91494ae9eacf.png)

question : Est-ce que nous ne demanderions pas leur titre ? histoire de nous donner la possibilité de vérifier

**Comment by nadinelouchart** [comment]
![Image](https://user-images.githubusercontent.com/121936073/218450751-d5c25887-ec2e-4837-80e3-2f07c91be3ee.png)

me pose des question sur le message - si je me mets a la place de l'utilisateur - je ne sais pas ce qu'est le référentiel ? propose le message suivant : l'UAI ou le SIRET de l'organisme n'ont pu être vérifié - Afin de nous aider à corriger et fiabiliser ces données - nous vous remercions de bien vouloir vous rapprocher de l'organisme concerné afin de l'inviter à vérifier et/ou a corriger ces données dans son logiciel de gestion. En cas de doute, vous pouvez également nous contacter (mail : support).

**Comment by Anne-Camille** [comment]
@nadinelouchart il y a ceci en recette, du coup est-ce selon toi suffisant ? 

![Image](https://user-images.githubusercontent.com/63646363/218789017-02e15ebd-a8a6-435d-9399-38c24fac4bdc.png)

**Comment by nadinelouchart** [comment]
oui je pense... à tester auprès des utilisateurs

**Comment by cathbaiona** [comment]
Parcours "Inviter un collaborateur" : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A288025&t=InS0uAyztLuQvl9p-1

Maquettes "Mes informations" : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A291116&t=InS0uAyztLuQvl9p-1

**Comment by nadinelouchart** [comment]
ok déjà pris en compte dans le nouveau parcours de connexion
