### ISSUE TITLE
Permettre à un gestionnaire de retirer un collaborateur

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2576]
![Image](https://user-images.githubusercontent.com/121936073/218484763-35d22ac4-7746-488c-b4da-158e97a5fcc4.png)

Fonctionnalités manquantes sur recette OF gestionnaire - manque le bouton retirer un collaborateur - a rajouter SVP !

**Comment by svengau** [comment]
https://github.com/mission-apprentissage/flux-retour-cfas/pull/2658

**Comment by nadinelouchart** [comment]
Recette OK - cool c'est ma première !!!
