### ISSUE TITLE
connexion parcours

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2579]
Revue générale des parcours d'inscription/connexion

- [ ] atelier irl 
- [ ] itw: maquettes

![Image](https://user-images.githubusercontent.com/121936073/218495178-2576c27d-bbe1-48eb-9a35-6e394fe096b7.png)

question : Est-ce que nous ne demanderions pas leur titre et organisme ? histoire de nous donner la possibilité de vérifier

**Comment by cathbaiona** [comment]
C'était déjà prévu dans les maquettes initiales :
- dès l'inscription pour l'OF et une DREETS mais en facultatif : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A288459&t=E8otMf631R6zCTle-1
- dans les paramètres du compte : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9011%3A283071&t=E8otMf631R6zCTle-1

**Comment by nadinelouchart** [comment]
Remise en question du parcours de connexion a retravaillé avec UI / PO
