### ISSUE TITLE
Mot de passe perdu devrait etre case insensitive

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2581]
si l'utilisateur réinitialise son mot de passe et que l'email n'est pas exactement celui en base (qui est toujours en minuscule), aucun email n'est envoyé.

**Comment by svengau** [comment]
PR https://github.com/mission-apprentissage/flux-retour-cfas/pull/2582

**Comment by Anne-Camille** [comment]
re7 ok
