### ISSUE TITLE
Problème Fiab établissement 33405590200053

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2590]
avec le siret 33405590200053, l'organisme est marqué comme étant fermé, alors qu'il y a bien un nouvel etablissement ouvert:

cf
https://www.societe.com/societe/ecole-de-design-nantes-atlantique-334055902.html
https://referentiel.apprentissage.onisep.fr/organismes/33405590200053/identite

**Comment by sbenfares** [comment]
Checker sur la recette la présence des 2 couples l'un fermé l'autre ouvert
