### ISSUE TITLE
Siret non trouvé dans le référentiel

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2606]
Dans le parcours inscription prévoir message à l'utilisateur en cas de Siret non trouvé dans le référentiel sur action a faire

- [x] Renvoyer l'utilisateur sur un lien l'annuaire des entreprises

**Comment by cathbaiona** [comment]
Maquette disponible ici :
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382%3A288421&t=InS0uAyztLuQvl9p-1
