### ISSUE TITLE
Le clic sur les tuiles de choix "Vous avez/ n'avez pas d'ERP" dans le cas d'un non transmetteur ne débranche sur rien

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2607]
![Image](https://user-images.githubusercontent.com/63646363/219399410-7e9f1926-ab80-4fd9-b419-481a853f929a.png)

Au clic sur les tuiles, retour sur le même écran.
Attendu : au clic sur la tuile vous avez un ERP => funnel choix de l'ERP et suite du parcours
Attendu : au clic sur la tuile vous n'avez pas d'ERP =>  écran d'upload de fichier et suite du parcours

**Comment by svengau** [comment]
PR https://github.com/mission-apprentissage/flux-retour-cfas/pull/2610

**Comment by Anne-Camille** [comment]
re7 : clic sur pas d'ERP => OK, en revanche impossible de revenir en arrière pour modifier mon choix
re7 : clic sur ERP => recette non terminée

**Comment by Anne-Camille** [comment]
Re7 : 
clic sur "j'ai un erp" funnel ok
clic sur "pas d'ERP" ok


Reliquats (autres cartes à faire)
-avec erp : un bouton inactif  (j'ai terminé de configurer) => au clic il ne se passe rien

![Image](https://user-images.githubusercontent.com/63646363/221581342-39841dae-094c-47a7-9112-c6fc76dd2d70.png)
- sans ERP : corriger la phrase "aucun effectif..."
- 

![Image](https://user-images.githubusercontent.com/63646363/221582323-9f8bcfca-bba6-428e-bf82-338e99da1f97.png)

**Comment by Anne-Camille** [comment]
@svengau recette ok (d'autres éléments annexes au bug principal sont repris dans d'autres cartes), je passe celle-ci en terminé !
