### ISSUE TITLE
Identifier les autres enquêtes (hors SIFA) et demandes de stats auxquelles doivent répondre les OF

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2611]
- [ ] enquête CDC
- [ ] enquête CEREQ 
- [ ] https://www.notion.so/mission-apprentissage/EDN-e44603bdd8974e1aa525197114e82868?pvs=4

![Image](https://user-images.githubusercontent.com/63646363/219421607-abf1d961-0a37-46fb-a3f3-ec37a1841e41.png)

**Comment by cathbaiona** [comment]
Notes : https://www.notion.so/mission-apprentissage/Enqu-tes-des-CFA-c99a314c32a04977ac4ff3054b02529d?pvs=4
