### ISSUE TITLE
Finalisation inscription impossible : perte du siret entre l'étape de saisie du siret et l'étape de saisie des coordonnées

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2614]
STUCK : reproductible sporadiquement

Parcours d'insription > je sélectionne "Tête de réseau" > à l'étape de saisie nom+prénom+courriel, le bouton "S'inscrire" n'est pas cliquable (disabled) car l'adresse email comporte des majuscules.
EDIT du 01/03/2023 : le pb n'est pas lié à la casse de l'email mais à la perte du siret entre la première et la seconde étape de l'inscription (voir capture : le siret bien que récupéré à l'étape d'avant n'apparaît plus à l'étape d'après)

![Image](https://user-images.githubusercontent.com/63646363/219590256-37d7f5be-7358-4472-9dcf-56e630c6c86d.png)

![Image](https://user-images.githubusercontent.com/63646363/219590404-d25b3141-f08c-4a15-9178-7b65c3b5cc99.png)

Souhaité : soit rendre l'email insensible à la casse, soit informer clairement l'utilisateur que le format d'email empêche de poursuivre avec une erreur "format d'email invalide" 

(idem erreurs formulaire) 

![Image](https://user-images.githubusercontent.com/63646363/220876927-833284ac-735d-4f10-832d-89e785d5ca3c.png)

**Comment by svengau** [comment]
en fait, nous mettons deja l'email en minuscule, et nous affichons aussi un msg d'erreur si besoin (cf screenshot)

![Image](https://user-images.githubusercontent.com/966303/221786669-cd53d1c5-5c2e-4ff3-96be-40146365a42e.png)


Le pb semble etre ailleurs ici. Tu as utilisé quel SIRET (je ne le vois pas sur ton screenshot) ?
