### ISSUE TITLE
Aucun email reçu pour poursuivre le parcours de procédure mdp oublié

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2620]
en recette : lorsque je clique sur mdp oublié et après avoir renseigné mon email, je ne reçois pas l'email de confirmation (non reçu sur mailhog)

recette réalisée avec un ancien email => refaire une recette avec une nouvelle inscription.

**Comment by svengau** [comment]
je viens de faire le test, et ca marche bien de mon coté

**Comment by Anne-Camille** [comment]
@svengau retesté à l'instant, devenu ok => je mets en terminé.
