### ISSUE TITLE
accès CFA gestionnaire non autorisé

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2623]
![Image](https://user-images.githubusercontent.com/121936073/220132436-801708d8-fc13-4824-9fbd-fbfb6dc10435.png)

process création de compte OK - mais impossibilité de finaliser la création du compte en tant que gestionnaire 

accès non autorisé

**Comment by nadinelouchart** [comment]
Carte 2612 - ACM

Lorsque je m'inscris en tant qu'OF, je sélectionne la permission (gestionnaire/lecteur/rédacteur) : un message d'alerte bloquant indique "une erreur technique est survenue".
Test réalisé avec le siret 78035020300011, uai absente

![Image](https://user-images.githubusercontent.com/63646363/219582390-0d84705a-b83c-4f1b-8908-880d59b22d98.png)



![Image](https://user-images.githubusercontent.com/63646363/219583735-af5767f4-7d6c-4723-ac18-f0352c6b109e.png)

**Comment by totakoko** [comment]
@nadinelouchart  Je regarde et je te tiens au courant !

**Comment by totakoko** [comment]
Après des corrections dans #2626, j'ai pu valider une création de compte + validation par l'admin. Est-ce que tu pourras retester ? @nadinelouchart
