### ISSUE TITLE
creation compte invité nogo

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2625]
![Image](https://user-images.githubusercontent.com/121936073/220139579-6ffd267a-5c82-4232-8a36-a24e5d58ea1d.png)

Compte OFRgestionnaire

lancement de l'invitation impossible - bouton "inviter" inactif

**Comment by nadinelouchart** [comment]
Suite recette https://github.com/mission-apprentissage/flux-retour-cfas/issues/2334 que je n'ai pas pu poursuivre

**Comment by totakoko** [comment]
Je n'ai pas pu reproduire ce bug. Si tu as le temps, est-ce qu'on pourrait voir ensemble pour reproduire ce comportement ?
