### ISSUE TITLE
Rédaction dictionnaire des données pour les OF

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2630]
- [x] rédiger le dictionnaire des données : WIP - charge courante : https://docs.google.com/document/d/19T7R8PLHRkEDxfUgOLAvjT6kgq3w1Ayf-R6oaeDsskE/edit?usp=sharing
- [x]  en lien avec https://docs.google.com/spreadsheets/d/1KI-Hq9viDZ9D6ZJD-SGrvOqX9eD37Rp5/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true
- [x] alimenter la FAQ / documentation

**Comment by cathbaiona** [comment]
@nadinelouchart Le document "dictionnaire des données" est à recetter. Une fois validé, il pourrait être mis rapidement en ligne sous forme de PDF pour nos organismes : il apporte des informations précieuses demandées ainsi que du sens.

https://docs.google.com/document/d/19T7R8PLHRkEDxfUgOLAvjT6kgq3w1Ayf-R6oaeDsskE/edit?usp=sharing
