### ISSUE TITLE
Connexion lecteur ou éditeur sans gestionnaire attaché

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2635]
Parcours de connexion : 

Un lecteur ou éditeur désire ouvrir un compte mais il n'existe pas de compte gestionnaire existant.

=> renvoi un e-mail au lecteur ou éditeur pour demander au responsable de l'organisation de créer un compte

Atelier prévu ce lundi 13 sur la base de https://whimsical.com/inscription-GwKu3BwtPa7jFSSFU2Xc5m

**Comment by cathbaiona** [comment]
Whimsical : https://whimsical.com/inscription-GwKu3BwtPa7jFSSFU2Xc5m
