### ISSUE TITLE
Faire une requête inscrits sans contrat à date du jour + dépôt sur resana

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2642]
**origine du besoin**
demande DGEFP auprès d'Anne

**to do**
réaliser un extract des dossiers apprenants inscrits sans contrat à la date du jour (pas d'autre filtre à appliquer)
déposer le doc sur resana
fournir le lien resana à Anne pour qu'elle puisse le transmettre

**Comment by felixat13** [comment]
Export prêt, en attente des accès Resana
