### ISSUE TITLE
Mettre à jour la document API

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2662]
**Origine du besoin**

Remontées : les erp constatent des retours API et découvrent ainsi que le siret est devenu obligatoire, les routes ont changé etc. La conséquence c'est que nous ne récupérons plus certains effectifs => cela dégrade le taux de couverture.

Mettre à jour les documents API

- [ ] Révision API V2

alimentation des Effectifs : https://documenter.getpostman.com/view/687182/Tzz5tyAp
récupération des Effectifs : https://documenter.getpostman.com/view/687182/UV5cBGFi
récupération des Indicateurs : https://documenter.getpostman.com/view/687182/Uyxho7Sg

- [ ] informer les ERP de la maj et leur transmettre la nouvelle doc (en distinguant les champs qui ont changé si possible) en profiter pour évoquer la dispo des stats de fiab et couv => rédaction contenu info et envoi  @nadinelouchart (@Anne-Camille si besoin)

**Comment by nadinelouchart** [comment]
CCou merci et en français cela veux dire quoi !? que la doc est prête à être communiqué ?

- [ ] m'envoyer un lien transmettable avec les explications de texte please ! merci ;) @svengau

**Comment by svengau** [comment]
Voila la doc: https://cfas.apprentissage.beta.gouv.fr/api/doc/

c une doc pour des decs techniques. La V3 est une proposition, à discuter avec l'équipe / les ERPs partenaires.

**Comment by nadinelouchart** [comment]
@svengau merci :) - j'ai mis le lien dans le notion dis moi juste si ok pour toi de le mettre là https://www.notion.so/mission-apprentissage/Acc-s-API-ERP-0698a40d4ab744a49ed700782d125b60

si non je te laisse corriger notamment la partie RCO

**Comment by svengau** [comment]
l'API est à destination des CFAs, je ne vois pas en quoi les RCOs sont impliqués. A discuter. cc @sbenfares
