### ISSUE TITLE
Terminer le flow "choix d'un ERP" de l'onglet mes effectifs (sur la version actuelle)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2663]
En tant qu'OF qui n'a jamais transmis ses effectifs, lorsque j'arrive sur l'onglet "mes effectifs". 
Je sélectionne "Vous avez un ERP" => une fois que j'ai sélectionné et que j'accède à l'écran tuto, un CTA "J'ai terminé de configurer mon ERP", ce CTA ne débranche sur rien.

Attendu : au clic sur le CTA il se passe qqchose (ex : une phrase qui indique qq chose comme : le tableau de bord recevra vos effectifs prochainement. Merci pour la transmission".)

**Comment by ClemLan** [comment]
Parcours proposé : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9669%3A284676&t=KBWxEsBoOmkTGjTj-1

**Comment by Anne-Camille** [comment]
re7 maquette ok, faire carte dev
