### ISSUE TITLE
Permettre à une DREETS d'inviter des collaborateurs (paramètres de partage de compte)

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2668]
Actuellement : un opérateur public ne dispose pas de l'action "paramètres".
Souhaité : un opérateur public dispose de l'action paramètres.
Au clic, cela ouvre le même écran que pour un OF sans les rôles lecteur/rédacteur/ gestionnaire.
Les utilisateurs qui sont présents sur cet écran sont ceux qui disposent de la même vue territoriale de l'opérateur public.
L'utilisateur qui accède à ces paramètres de compte peut : 

- inviter un collaborateur (par défaut sur la même vue)
- modifier ses propres informations
- supprimer son propre compte
- faire une demande de modification ou de suppression d'un collaborateur auprès de l'admin

L'utilisateur qui accède à ces paramètres de compte ne peut pas : 

- supprimer un collaborateur
- modifier les informations d'un collaborateur

**Comment by cathbaiona** [comment]
Maquettes en cours : 

- [Paramètres](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9888%3A294297&t=fYXKlYOAtTyltHXI-1) du compte
- [Roles et habilitations ](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9888%3A291828&t=fYXKlYOAtTyltHXI-1)

**Comment by nadinelouchart** [comment]
ok pour moi @nadinelouchart a part un petit détail "mot à changer"

Vérifier quand même que nous sommes bien en ligne avec le nouveau parcours de connexion
