### ISSUE TITLE
ISCAE fiabilisation

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2678]
Suite échange enter violaine et ISCAE note ci-dessous - travaille de fiabilisation

https://www.notion.so/mission-apprentissage/31100f7948304feca381151771a1ebf7?v=d0dcd7776ae84df69729d2094f704bdf&p=69e18e104930491bb3cee8617f40bfa6&pm=s

**Comment by sbenfares** [comment]
Apparait comme de la fiabilisation d'effectifs

**Comment by sbenfares** [comment]
Après investigations, il semblerait que ces candidats ont été « mal inscrit » par notre client.

L’envoi des candidats se fait automatiquement toutes les nuits. Et si un candidat est mal inscrit puis est corrigé seulement le lendemain, il sera envoyé avec les autres candidats durant la nuit, puis ne sera plus envoyé le lendemain s’il  ne plus apprenti. Il semble cependant que vous gardez ces candidats (à confirmer avec Samir).

Il ne s’agit pas là d’un abandon, mais d’un inscrit sans contrat mis par erreur en apprentissage par le client.

 

Restant à votre disposition pour en discuter.

 

Bien Cordialement,

**Comment by sbenfares** [comment]
En attente échange SC Form
