### ISSUE TITLE
CFA ESCAM - fiabilisation

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2679]
Suite à contact entre violaine et l'ESCAM

https://www.notion.so/mission-apprentissage/31100f7948304feca381151771a1ebf7?v=d0dcd7776ae84df69729d2094f704bdf&p=6d9637c1423043fd91d1292ae52f3785&pm=s

https://docs.google.com/spreadsheets/d/1vbD2xOnocGiIlr7EsKr__owBWvcqhWiu/edit?usp=sharing&ouid=108278837304609529635&rtpof=true&sd=true

**Comment by sbenfares** [comment]
Apparait comme de la fiabilisation d'effectifs

**Comment by sbenfares** [comment]
En attente échange SC Form
