### ISSUE TITLE
Remettre en place le visuel "déployé" sur les cartes du kanban

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2683]
Besoin : lorsque la recette est ok, et que le déploiement en prod est effectué, le PO peut voir que la mep a été réalisée et glisser la carte dans "terminé"

To do : 
Remettre en place le label automatique (voir avec Antoine si difficulté) 

( ce label qui évolue en fonction de l'avancée de la PR) 

![Image](https://user-images.githubusercontent.com/63646363/223989922-99ce57ea-6732-41a7-b71c-a042105568b0.png)

**Comment by svengau** [comment]
@antoinebigard tu as une idée de la lib / plugin qui faisait ça ?

**Comment by svengau** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
