### ISSUE TITLE
Analyse des organismes de Normandie n’apparaissant plus

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2691]
Plusieurs CFA n'apparaissent plus ou ne transmettent plus depuis la mep du 16/01 : 
-  0610770F -  77811608700140 - > BATIMENT CFA ALENCON
-  0611206E - 40141754800039 -> ETPN A SAINT PATERNE
-  0142269R - 50305387800032 - > CFA PSS NORMANDIE : apparaît dans le tdb mais avec une date de dernière transmission au 16/01/23
-  0271871M

To DO

- [x] tableau avec tous les organismes qui ne transmettent plus depuis le 16/01 => Félix
- [ ] vérifier si le fix  passé le 09/03 serait de nature à corriger les écarts relevés par la Normandie => Samir
- [ ] investigation sur les raisons pour lesquelles les établissements ont disparu/ne transmettent plus

**Comment by felixat13** [comment]
Organismes ne transmettant plus depuis le 16/01 : https://cfas.apprentissage.beta.gouv.fr/metabase/question/498-liste-organismes-qui-ne-transmettent-plus-depuis-le-16-01-2023

**Comment by sbenfares** [comment]
lien possible lors de la correction de #2787

**Comment by sbenfares** [comment]
Premières analyse sur : 

- 0610770F - 77811608700140 - > BATIMENT CFA ALENCON : je le trouve comme fiable et transmettant avec des effectifs : [](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/101-utilitaire-analyses?uai=0610770F&siret=77811608700140)

**Comment by sbenfares** [comment]
Ecrire à l'organisme qui ne transmets plus depuis janvier : 50305387800032

**Comment by sbenfares** [comment]
0271871M : pas de SIRET donc ne rentre pas dans le TDB

- [ ] Contacter pour lui demander de fournir le SIRET

**Comment by sbenfares** [comment]
RAF : 

0142269R - 50305387800032 - > CFA PSS NORMANDIE : apparaît dans le tdb mais avec une date de dernière transmission au 16/01/23 TODO RAF

**Comment by sbenfares** [comment]
Vu qu’il ne fournit pas de SIRET l’organisme ne passe pas la fonction de resolveOrganisme, il faut ajouter une fiabilisation manuelle + un fix sur le schemaTech (ZOD)
