### ISSUE TITLE
Fiabilisation : investiguer rupturants sans contrat depuis + 6 mois

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2693]
Effectifs rupturants depuis + de 6 mois => devraient figurer dans l'indicateur abandons (restent stockés comme rupturants)
Effectifs inscrits sans contrat depuis + de 3 mois => devraient figurer dans l'indicateur abandons

**To DO**

- [x] voir avec Félix : extract des concernés avec leur statut courant => Félix
- [x] investigation : acm : https://www.notion.so/mission-apprentissage/Sans-contrat-90-jours-et-Rupturants-180-jours-df53a15d91e34adaa35cde2bbac8843f?pvs=4
- [x] (tenir compte de https://mission-apprentissage.notion.site/SC-Form-corrections-apporter-da31d2a3cf3349d2a897b8ddf62f582f)

**Comment by felixat13** [comment]
Liste, nombre et répartition selon le temps écoulés des rupturants et inscrits sans contrats OK ✅
Dispo sur le [dashboard suivant](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/108-requetes-effectifs
)

![Image](https://user-images.githubusercontent.com/26534407/226315587-49cb8c91-11a9-4515-8140-6cc6731b1d48.png)

**Comment by Anne-Camille** [comment]
@felixat13 te semble-t-il possible, sur la liste des "inscrits sans contrat", de filtrer sur l'historique de statuts : je voudrais savoir combien on a de dossiers pour lesquels la date de statut "en contrat" est antérieure à la date de statut "inscrit en formation" ?

**Comment by felixat13** [comment]
@Anne-Camille pour le 2ème point j'ai créé un ticket pour les devs, afin de fixer la colonne erp de la collection organisme.
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2834

**Comment by Anne-Camille** [comment]
@felixat13  j'ai un écart entre ce qui est affiché en front (apprenti) et ce qu'on a dans les bases (inscrit sans contrat)
exemple sur l'UAI 0511649R, apprentie Lambin Floriane



![Image](https://user-images.githubusercontent.com/63646363/229050417-c950d815-57a6-4c8e-8ecf-cce051f6ac95.png)
