### ISSUE TITLE
Créer 2 filtres supplémentaires : Domaine de formation / Domaine d'emploi

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2699]
Doc de référence : https://docs.google.com/spreadsheets/d/1KIS_J3bnufZKXNtI_XyKidJqZtzRssRl/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true

**Origine du besoin**
Tests et retours utilisateurs (DREETS et OPCO) : en tant qu'utilisateur, je veux filtrer les données par secteur professionnel.

=> voir si sujet TCO/kit apprentissage (Antoine & David)

**Specs**

Installer 2 nouveaux filtres intitulés "Domaine de formation" et "Domaine d'emploi": 
Voir API TCO (tables de correspondance, développée par la mission normalement intégrée dans l'API RCO > contact Antoine ; https://tables-correspondances.apprentissage.beta.gouv.fr/login) pour le lien entre formacode>RNCP

- [x] Domaine de formation : 
Sur la base de la correspondance RNCP > formacode : https://www.data.gouv.fr/en/datasets/repertoire-national-des-certifications-professionnelles-et-repertoire-specifique/, nous avons la correspondance RNCP = grand domaine du formacode (grands domaines et correspondances RNCP/FORMACODE récupérables ici : https://www.data.gouv.fr/en/datasets/repertoire-national-des-certifications-professionnelles-et-repertoire-specifique/)
Nous pouvons donc afficher un filtre grand domaine du formacode > sous filtre libellé formacode > sous filtre RNCP ou ensemble de RNCP liés à ce formacode
Sur cette première version de filtre, nous affichons uniquement le grand domaine du formacode (pas les sous filtres liés au sous-domaine et aux RNCP) ; il existe 14 grands domaines.
A la sélection du grand domaine de formation, les indicateurs sont filtrés : 
un apprenant est inscrit dans une formation à laquelle correspond un ou plusieurs RNCP : ce(s) RNCP(s) sont rattachés à un ou plusieurs grands domaines du formacode.
Ex : un apprenant qui fait une formation en coiffure > RNCP34670 > grand domaine formacode correspondant = Commerce, marketing, finance. ([voir doc](https://docs.google.com/spreadsheets/d/1KIS_J3bnufZKXNtI_XyKidJqZtzRssRl/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true). Quand je clique sur "Commerce, marketing, finance", cet effectif remonte (parmi les autres effectifs dont les RNCP corresponde au grand domaine).

- [ ] Domaine d'emploi
Sur la base de la correspondance RNCP > ROME : nous avons la correspondance RNCP = grand domaine du ROME.
Nous pouvons donc afficher un filtre grand domaine du ROME (grands domaines du ROME récupérables ici : https://pole-emploi.io/data/api/rome?tabgroup-api=documentation&doc-section=api-doc-section-r%C3%A9cup%C3%A9rer-le-d%C3%A9tail-d-un-m%C3%A9tier) > sous filtre sous domaine du rome > sous filtre RNCP ou ensemble de RNCP liés à ce ROME.
Sur cette première version de filtre, nous affichons uniquement le grand domaine du ROME (pas les sous filtres liés au sous-domaine et aux RNCP) ; il existe 14 grands domaines, de A à N.

**To do**

- [ ] Typeform : à adresser DREETS /DDETS / OPCO : objectif, est ce que les filtres et sous-filtres proposés seraient utiles ou pas

**Comment by cathbaiona** [comment]
@Anne-Camille Voici donc (sur le modèle du _décollapse_" un [premier jet](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=10230%3A307490&t=ZpeGauwKI51R5pup-1) avec V1 (incluant 2 niveaux du ROME) et V2 (incluant 3 niveaux)

**Comment by Anne-Camille** [comment]
hello @cathbaiona celle-ci est en recette et déjà recettée ensemble ou tu veux encore travailler des éléments (je ne l'avais pas déplacée quand on en avait parlé) ? car si tout est ok, je fais la carte dev tt de suite !

**Comment by Anne-Camille** [comment]
Prise dans la carte tech suivante : https://github.com/mission-apprentissage/flux-retour-cfas/issues/2878
