### ISSUE TITLE
Mise à jour des bulle d'aide utilisateur

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2702]
Suite maquette carte https://github.com/mission-apprentissage/flux-retour-cfas/issues/2580

- [x] changer message selon maquette figma

Voici le lien vers le tooltip "Alerte" :
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9791%3A287590&t=ewgqoZpvdWmLQbVv-1

**Comment by Anne-Camille** [comment]
Ok bulle mise en place, mais fautes à corriger, cf. https://github.com/mission-apprentissage/flux-retour-cfas/issues/2766
