### ISSUE TITLE
Ajouter 2 champs dans le formulaire d'inscription

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2703]
Suite à validation maquette de la carte https://github.com/mission-apprentissage/flux-retour-cfas/issues/2536

https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A291116&t=ewgqoZpvdWmLQbVv-1

- [ ] rajouter la notion

![Image](https://user-images.githubusercontent.com/121936073/224318152-9dbf28de-3309-40b6-a008-fa1d373e6542.png)

**Comment by Anne-Camille** [comment]
@cathbaiona @nadinelouchart il ne me semble pas que ça ait été repris dans les nouvelles maquettes revues ce matin ?

**Comment by cathbaiona** [comment]
@Anne-Camille @nadinelouchart En effet, ces 2 champs concernant la création d'un compte utilisateur **OF**, ils ont disparu du formulaire du socle commun. On les retrouve désormais dans la page "Mes informations" des paramètres de compte :
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A291116&t=VcCbdzcWPfYZ7cm3-1
Pour encourager les utilisateurs à compléter leur profil, je souhaiterai rajouter un bandeau d'information sur la page "Mon tableau de bord" (exemple ci-dessous, texte à adapter)


![Image](https://user-images.githubusercontent.com/108516993/226292579-1f42b580-0179-45f0-ab7d-7ac9577f932d.png)

**Comment by svengau** [comment]
@totakoko je crois avoir vu un des 2 champs dans ta PR relative aux permissions. Tu confirmes ? 

@cathbaiona du coup, si je comprends bien, il ne faut pas mettre ces 2 champs au niveau de l'inscription, mais dans la rubrique "Mon compte > Mes informations" ?

**Comment by nadinelouchart** [comment]
@sven est-ce toujours d'actualité ?

**Comment by svengau** [comment]
@nadinelouchart  de ma comprehension, ce champs est sur le profil utilisateur, et plus au niveau de l'inscription. AMHA, une fois que l'utilisateur a été enregistré, et son compte validé par qq, je ne vois pas l'interet de demander cette information a postériori.
