### ISSUE TITLE
Fournir nom d'utilisateur et mot de passe à l'OPCO EP pour utilisation API TDB de récupération des effectifs

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2704]
demande Antoine Bossan du 10/03 : notre DSI nous demande un nom d'utilisateur et un mot de passe pour que l'on puisse utiliser les APIs sur l'environnement de dev.

- [x] fournir clé => sven
- [x] répondre A. Bossant =>acm

**Comment by antoinebigard** [comment]
Nous avons besoin de finir la spec API v3 // Authentification Client avant toute création de nouveaux accès

**Comment by Anne-Camille** [comment]
Concernait la demande d'accès à la V2 => envoi du mail suivant le 17/03/2023



Bonjour Antoine,


Nous réalisons de changements majeurs de notre V2 actuelle vers la V3 : les évolutions portent notamment sur le mécanisme d'authentification et le modèle de données qui sera plus exhaustif.


Si vous réalisez des développements sur la base de l'API V2, il faudra prévoir d'intégrer par la suite les modifications liées au déploiement de la V3 (prévision mai). L'API V2 ne sera plus maintenue à partir de fin juin.


Nous vous proposons, si vous avez besoin des chiffres de façon régulière jusqu'au mois de mai, de vous transmettre les éléments par fichier plat (c'est-à-dire rejouer la requête précédemment transmise), afin de vous éviter de faire 2 fois les développements.


Si toutefois vous préférez tout de même accéder à la V2 dès maintenant, nous vous enverrons les codes.


Nous sommes à l'écoute de ce qui vous convient le mieux compte tenu de ces précisions.


Bien cordialement,

**Comment by Anne-Camille** [comment]
réponse 20/03 : attendent la V3
