### ISSUE TITLE
Nouvelle fonctionnalité : Pouvoir modifier son mot de passe depuis son compte

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2705]
Suite recette OF dans mon compte manque le parcours 'pouvoir modifié son mot de passe"

![Image](https://user-images.githubusercontent.com/121936073/224332953-71931bf5-80c2-4fad-b2ea-0999c1bf08c9.png)

- [x] Maquetter parcours 'pouvoir modifié son mot de passe" sur compte OF / Operateur Public / Réseaux
- [ ] valider le parcours technique avec les DEV
- [ ] après validation maquette créer carte tech

**Comment by cathbaiona** [comment]
@nadinelouchart [Maquettes Figma pour OF](https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9518%3A291115&t=VcCbdzcWPfYZ7cm3-1) -> onglet "Mes informations"

**Comment by nadinelouchart** [comment]
@cathbaiona Maquette validé pour cette partie là :)

**Comment by cathbaiona** [comment]
@nadinelouchart Du coup, je me suis désassignée de cette carte, et j'ai mis @totakoko pour la suite.

**Comment by totakoko** [comment]
Modifier son MDP => faisable :smile:

**Comment by nadinelouchart** [comment]
ok carte tech dev à suivre https://github.com/mission-apprentissage/flux-retour-cfas/issues/2863
