### ISSUE TITLE
Revoir systeme de permissions

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2706]
Test opérateur public DRAAF - lors de la création du compte et demande de permissions avec choix d'une seule régions - pour quelle raison avons nous 454 permissions au lieu de 1 seule à valider ?

![Image](https://user-images.githubusercontent.com/121936073/224370333-b7cfafa6-5f78-4bb5-a466-26c6d4a5b745.png)

Permettre d'avoir une seule permission pour l'ensemble des 454 établissement de la ou les régions concernées

**Comment by svengau** [comment]
le systeme actuel prend tous les organismes d'un territoire (department, region, academie), et crée une permission par organisme. Deja discuté avec @totakoko et @antoinebigard , on va changer ca pour n'avoir qu'une seule entrée.

**Comment by nadinelouchart** [comment]
OK même sujet pour les DREETS
