### ISSUE TITLE
Import d'effectifs sans ERP : calcul des indicateurs selon données transmises via template

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2707]
Suite de la  https://github.com/mission-apprentissage/flux-retour-cfas/issues/2538

Le template d'effectifs et le mapping ont été modifiés pour tenir compte des futurs indicateurs et pour alléger la partie mapping pour l'utilisateur.

Dans la période transitoire entre les indicateurs tels qu'ils existent aujourd"hui et les indicateurs de demain, les données reçues doivent être traduites en indicateurs tels qu'ils existent aujourd'hui.

Pour traduire les événements en indicateurs apprenti/inscrit sans contrat/rupturant/abandon, se référer à l'onglet 2 de [ce fichier.](https://docs.google.com/spreadsheets/d/1KI-Hq9viDZ9D6ZJD-SGrvOqX9eD37Rp5/edit?rtpof=true&sd=true#gid=953740490)

**Comment by nadinelouchart** [comment]
@sbenfares est-ce toujours d'actualité ?
