### ISSUE TITLE
Je peux poursuivre l'inscription avec un siret fermé

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2726]
Siret détecté fermé (13001050700080)
Je peux malgré tout poursuivre le process d'inscription (bouton suivant actif) alors que je ne devrais pas : 

![Image](https://user-images.githubusercontent.com/63646363/224987563-831c03f1-fa0d-4adc-98e8-fd22b5b7718f.png)

L'écran suivant indique une information contraire et erronée (siret en activité) : 

![Image](https://user-images.githubusercontent.com/63646363/224987390-5edb283d-3110-4c22-ba6a-7b221231644c.png)

**Comment by svengau** [comment]
https://github.com/mission-apprentissage/flux-retour-cfas/pull/2731

**Comment by Anne-Camille** [comment]
re7 ok sur l'exemple, pas pu poursuivre (environnement recette cassé), retester avec un profil OF 19010017200013

**Comment by Anne-Camille** [comment]
re7 ok
