### ISSUE TITLE
Requêtes pour l'étude des facteurs de réussite des CFA agricoles

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2747]
**Besoin**

Sur le périmètre des établissements du MASA ([liste des établissements avec code DGER et SIRET ici](https://docs.google.com/spreadsheets/d/1qGwm1lc0QpbO83D8KdugLM2dXSvXJskb/edit?usp=share_link&ouid=117555389785053708113&rtpof=true&sd=true)) : 

- [x] - taux de rupturants et nombre d'abandons par établissement ; 
- [x] - taux de rupturants et nombre d'abandons par niveau de diplôme agricole (CAP, Bac pro, BTSA, CS, BP)
- [x] - taux de rupturants et nombre d'abandons par spécialité de diplôme (avez-vous besoin dans ce cas que nous vous fournissions la liste de tous les diplômes en apprentissage ?)
- [ ] - taux de rupturants et nombre d'abandons par sexe ; => donnée non dispo tdb
- [x] - taux de rupturants et nombre d'abandons par âge ; 
- [x] - taux de rupturants et nombre d'abandons par région ;

A partir du fichier des établissements, nous aurons besoin de savoir le taux de couverture de ces indicateurs. 

Enfin, pour situer ces données du périmètre MASA dans le paysage national de l'apprentissage, nous aurions besoin de références nationales : 
- taux de rupture national par niveau de diplôme (CAP, bac pro...), par région, par sexe (non dispo tdb) et total. 
- taux d'abandon par niveau de diplôme (CAP, bac pro...), par région, par sexe (non dispo tdb) et total.

**Comment by felixat13** [comment]
@Anne-Camille pour info je vais ajouter au fur et à mesure les requêtes en bas de ce [dashboard](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/107-requetes-organismes), sous la section "Requêtes CFA Agricoles"
