### ISSUE TITLE
Extraire la liste des organismes qui ne transmettent pas/plus

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2751]
- [x] réaliser l'extract => Félix
- [x] filtrer l'extract sur Grand Est (44)
- [x] envoyer l'extract à la dreets GE avec readme en onglet 1=> PO

>Sur l'extract figure le statut de fiab pour chaque organisme 
>On doit pouvoir filtrer sur les infos suivantes : 

- ne transmettent plus depuis plus de 60j + date de la dernière transmission 

- n'ont jamais transmis

- transmettent + date de la dernière transmission

**Origine du besoin Grand Est**

Demande lors de la réunion https://www.notion.so/mission-apprentissage/DREETS-GE-Pr-paration-r-union-525a31fe480a4380b8c4ccf975da8185?pvs=4
Objectif : la dreets adresse des mails mieux ciblés selon la situation de l'OF

**Comment by felixat13** [comment]
@Anne-Camille voilà l'extract, également transmis à Anne : https://cfas.apprentissage.beta.gouv.fr/metabase/question/503-liste-organismes-qui-ne-transmettent-pas-region-grand-est
