### ISSUE TITLE
Vue opérateur public : présenter les indicateurs sous forme de dataviz

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2755]
**Origine du besoin**

Les dreets/ddets ont besoin d'éléments pour animer leurs réunions autour de l'apprentissage.

**Souhaité**

Sur la vue territoriale, mettre en place un iframe pour accueillir la dataviz selon le périmètre de l'utilisateur (https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/106-dataviz-indicateurs).

- répartition volumes apprentis/rupturant/sans contrat/abandon
- info taux de couv et indice de fiab 

**To do**

- [x] réaliser les requêtes pour chaque périmètre => @felixat13 
- [ ] mettre en place les iframe => @dev

![Image](https://user-images.githubusercontent.com/63646363/225870536-b9e2b10a-8685-410a-994f-1b7b07ad9b61.png)

**Comment by felixat13** [comment]
Une première version du dashboard est disponible [ici](https://cfas.apprentissage.beta.gouv.fr/metabase/dashboard/117-vue-territoriale-operateurs-publics). @Anne-Camille @cathbaiona si c'est bon pour vous, on peut envoyer en dev :)

**Comment by felixat13** [comment]
Hello @svengau, voici l'iframe du dashboard Metabase à intégrer dans un nouvel onglet sur la vue territoire. Je te laisse voir avec Catherine pour la partie front !
`<iframe
    src="https://cfas.apprentissage.beta.gouv.fr/metabase/public/dashboard/e809d2c2-a3b7-47c4-ab28-2a72c6d687ce"
    frameborder="0"
    width="800"
    height="600"
    allowtransparency
></iframe>`

**Comment by svengau** [comment]
ping @cathbaiona
