### ISSUE TITLE
envoyer fichier non transmetteurs à l'ensemble des DREETS

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2768]
**Objectif**
Acquisition de nouveaux transmetteurs => les dreets peuvent contacter les OF qui ne transmettent pas pour les inciter à le faire.

**To do**

- [x] réaliser une requête par région sur la base de https://github.com/mission-apprentissage/flux-retour-cfas/issues/2751 => félix
- [x] ajouter un filtre : exclure les organismes dont la nature est responsable (en effet, ils n'ont pas d'effectif à transmettre) => félix (edit acm: mis à done car info finalement incorrecte)
- [x] @nadinelouchart @felixat13 j'ai fait [un draft de l'onglet "readme" ](https://docs.google.com/spreadsheets/d/1WI8usa4Xi2s0q2lm8pcjZaZ6z5opNGBI/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true)à ajouter aux fichiers avant transmission : votre relecture est bienvenue 
- [ ] envoyer les requêtes aux référents apprentissage de chaque région avec mode opératoire et message d'info ( quoi faire des données , proposition de message pour solliciter les non transmetteurs) => nadine (transmission dreets PACA par ac le 29/03/23)

**Comment by Anne-Camille** [comment]
@felixat13 merci, suite remontée de besoin de cet apm, est-il possible d'ajouter l'adresse des étab parazar stp ?

**Comment by felixat13** [comment]
@Anne-Camille c'est ajouté :) Le format est pas hyper joli mais c'est comme ça qu'on l'a en base

**Comment by felixat13** [comment]
C'est bon pour moi @nadinelouchart !

**Comment by Anne-Camille** [comment]
@felixat13 j'ai envoyé le fichier des non-transmetteurs suite demande de dreets PACA, en exportant la liste je n'ai pas vu l'ajout des coordonnées (https://github.com/mission-apprentissage/flux-retour-cfas/issues/2791) est-ce qu'il serait possible de les afficher dans le format d'export ?
@nadinelouchart ce n'est pas une donnée sensible mais une donnée personnelle, je ne me souviens plus des préco d'Osiris sur l'envoi des mails/tel pro ?

**Comment by felixat13** [comment]
@Anne-Camille Ah pardon je n'avais pas vu que le champ avait été ajouté en prod. Je vais l'ajouter à la requête, par contre je pense qu'on aura beaucoup de cases vides, car ce champs n'est pas souvent rempli, et je fais un join sur les couples UIA/SIRET du référentiel donc possible que certains ne matchent rien.

**Comment by Anne-Camille** [comment]
@felixat13 pas de pb, merci et c'était mon erreur => je n'avais pas vu que la carte était en in progress, désolée ! Normal qu'on n'ait en effet pas toutes les infos de contact ! J'ai pu voir aussi que le champ adresse n'était pas non plus systématiquement rempli ça c'est plus curieux, je n'ai pas creusé pour voir si cela correspondait en particulier à des étab non fiables (je regarderai demain)

**Comment by felixat13** [comment]
@Anne-Camille @nadinelouchart colonne contacts ajoutée à l'export des non transmetteurs par région
(https://cfas.apprentissage.beta.gouv.fr/metabase/question/504-liste-organismes-qui-ne-transmettent-pas-filtre-region?region=93)

**Comment by nadinelouchart** [comment]
@felixat13 merci - même au vue de sont taux de remplissage j'ai quelques doutes sur son utilité - a regarder comment compléter cette colonne de façon optimisé

**Comment by felixat13** [comment]
Pour info cette colonne vient directement du référentiel, effectivement je ne sais pas comment est effectuée la collecte à ce niveau.
