### ISSUE TITLE
Investiguer le pbs des OF qui ne transmettent plus depuis le 16/01

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2775]
Perte de +23K effectifs => liste d'OF, tous ERP confondus, qui ne transmettent plus depuis le 16/01
Trouver quelle en est la raison + corriger si possible (ou communiquer auprès des ERP el cas échéant).

Liste disponible ici => https://cfas.apprentissage.beta.gouv.fr/metabase/question/498-liste-organismes-qui-ne-transmettent-plus-depuis-le-16-01-2023

**Comment by Anne-Camille** [comment]
-  erreurs liées au siret (siret_etablissement) non renseigné chez certains clients, pourtant le champ est facultatif dans la documentation :

400 - {"status":"ERROR","message":"missing parameter `siret`","error":{}} ERREUR

- 400 - {"status":"ERROR","message":"L'organisme ayant le SIRET 30282378600025 existe déja en base avec un UAI différent : 0281156E","error":{}}

- 400 - {"status":"ERROR","message":"L'organisme ayant l'UAI 0763164B existe déja en base avec un SIRET différent : 19762762300196","error":{}}

- erreurs HTTP 429 (too many requests) sur l'appel à l'API "entreprise"

- API Mission Apprentissage : Erreur lors de l'appel au WebService pour le bloc 1 :
 400 - {"status":"ERROR","message":"Document failed validation"}

**Comment by nadinelouchart** [comment]
- [ ] Après, constat bug suite problème ingestion le 24/04 - vérifier que ce ne soit pas lié @svengau

**Comment by svengau** [comment]
@nadinelouchart, clairement pas lié, puisque le nouveau process d'ingestion a été mis en place le 22/03

**Comment by svengau** [comment]
TLDR;
j'ai l'impression qu'avant le 16 janvier, nous orientions les effectifs vers le mauvais organisme (meme UAI), et que cela a été corrigé depuis. Comme le mauvais organisme ne transmet pas, sa date de derniere transmission n'est plus maj. BTW, nous avons des doublons (se servir du couple ID ERP apprenant +source pour les identifier).

Dans le detail:

Quelques infos supplémentaires :
1/ organisme par ERP > ymag: 101, scform: 10, gesti: 126
2/ j'ai fait une recherche avec le couple SIRET + UAI retourné par metabase, et je ne trouve aucun dossier envoyé via l'API depuis que nous avons mis en place le nouveau process d'ingestion. Sachant que ymag nous envoie toute la base toutes les nuits, et que le nouveau process d'ingestion accepte tous les dossiers entrants, on aurait au moins du trouver 

Un exemple, organisme id: [635acfbe5e798f12bd91ada7](https://cfas.apprentissage.beta.gouv.fr/admin/organismes/635acfbe5e798f12bd91ada7) (siret: "77955453400023"), fiable, envoie par ymag, derniere transmission le 16 janvier, 2281 effectifs sur 2021-2022, 2308 sur 2022-2023 (donc pas un pb de periode). 
 ➡  En regardant de plus près, on a des apprenants qui ont "glissé" vers un autre organisme associé (meme UAI) (exemple: {id_erp_apprenant: "10039690", annee_scolaire: "2022-2023"})
