### ISSUE TITLE
mongodb authentication

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2779]
Une premiere PR a été pushé, mais a priori on peut toujours se connecter sans auth.

[#2709](https://github.com/mission-apprentissage/flux-retour-cfas/pull/2709)

**Comment by totakoko** [comment]
Fichier /opt/flux-retour-cfas/.overrides/docker-compose.common.yml non à jour. Peut-être un setup-vm à faire ? @sbenfares
