### ISSUE TITLE
Ajouter une colonne effectifs_2023 dans la collection organismes

### ISSUE THREAD

**Issue by felixat13** [mission-apprentissage/flux-retour-cfas#2797]
Pour des besoins analytiques, il serait très utile d'avoir le nombre d'effectifs sur l'année scolaire en cours pour chaque organismes (de la même façon qu'on a déjà le nombre d'effectifs total).

Les valeurs d'années scolaire à prendre en compte seraient : `{ $in: [ "$annee_scolaire", ["2022-2023", "2023-2023"]]}`

**Comment by felixat13** [comment]
@svengau est-ce qu'éventuellement si c'est rapide il serait aussi possible d'ajouter la colonne "qualiopi" existante dans organismesReferentiel dans la collection Organismes ? 🙏

**Comment by svengau** [comment]
@felixat13 oui, c rapide et on peut bien sûr denormaliser la data. Avant de considérer cette option, un $lookup ne suffit pas ?

**Comment by felixat13** [comment]
Hello @svengau 
- qualiopi, un $lookup pourrait suffire mais il faut le faire à chaque requête c'est un peu lourd, ça serait très pratique de l'avoir directement dans la table !
- Parfait pour la colonne effectifs_current_year_count !
