### ISSUE TITLE
Siret non trouvé dans le référentiel "techdev"

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2802]
reprendre maquette figma 

https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9382-288421&t=p5oaC6yg5QKsH7vq-0

- [ ] Intégrer le message siret manquant

selon carte https://github.com/mission-apprentissage/flux-retour-cfas/issues/2606

**Comment by totakoko** [comment]
@nadinelouchart C'est toujours d'actualité ?
Actuellement, on affiche un message d'erreur si le siret n'est pas trouvé ni dans notre base de données (qui contient le référentiel), ni dans l'API entreprise. Le message est "Ce SIRET n'existe pas. Veuillez vérifier à nouveau".

**Comment by nadinelouchart** [comment]
OK donc du coup c'est à faire ;) - merci

**Comment by totakoko** [comment]
Pardon, dans la carte d'origine, c'était indiqué `en cas de Siret non trouvé dans le référentiel`, d'où ma confusion.
Donc pour clarifier, si on ne trouve pas l'organisme avec l'api entreprise, on affiche le message d'erreur avec un lien vers la page d'accueil de l'annuaire des entreprises.
Je fais ça :+1:
