### ISSUE TITLE
Un compte en attente de validation peut voir tous les organismes

### ISSUE THREAD

**Issue by svengau** [mission-apprentissage/flux-retour-cfas#2806]
Un compte en attente de validation peut voir tous les organismes dans "mon espace > mes organismes". Au clic sur un organisme, l'acces est refusé.
Une fois la demande validé, il ne peut accéder qu'à son organisme.

**Comment by antoinebigard** [comment]
https://github.com/mission-apprentissage/flux-retour-cfas/blob/master/ui/components/Page/components/NavigationMenu.jsx#L104

https://github.com/mission-apprentissage/flux-retour-cfas/blob/master/ui/components/UserWrapper/UserWrapper.jsx#L35 ????

**Comment by antoinebigard** [comment]
pour moi pas de bug

**Comment by svengau** [comment]
commit https://github.com/mission-apprentissage/flux-retour-cfas/commit/f8c05667c666ca92bdcd5e4e0e25be9a4a6bbad2
