### ISSUE TITLE
Mise à jour et validation de nouvelle CGU

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2828]
Dans le cadre du nouveau processus d'inscription les CGU sont validé sur le formulaire de connexion

Dans le cas de mise à jour des CGU - l'utilisateur doit impérativement valider ces dernières avant d'accéder à nouveau au TdB

- [ ] @catherine créer la maquette de la pop up
- [ ] intégrer la pop-up sur le chemin renouvellement des CGU auprès des utilisateurs connectés ou non

**Comment by cathbaiona** [comment]
Pour info @nadinelouchart , j'ai connu cette situation en me connectant à mon compte Ameli.

![Image](https://user-images.githubusercontent.com/108516993/229784174-b54e8629-211c-4ea8-9104-a6c1d75ab70e.png)

**Comment by cathbaiona** [comment]
Voici les maquettes (WIP) : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=10380%3A306855&t=TsBd2pmlsvH4mrJB-1

**Comment by totakoko** [comment]
Actuellement on a une modale en plein écran, qui devrait suffir pour un bon bout de temps :wink:. Personnellement, la solution 1 me dérange un peu car les liens de navigation sont apparents or toute action devrait être bloquée.

**Comment by cathbaiona** [comment]
Si on part sur la modale, il faut garder le lien "fermer" et on perd donc le caractère obligatoire de l'action (accepter les CGU). L'utilisateur peut donc "échapper" à cette action.
[Image](https://user-images.githubusercontent.com/108516993/230051160-324a627c-5894-4190-beb0-2f69d59110af.png)
PI : voici ce que dit le [DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/modale/)
Si l'on part sur l'option 1, le Header reste en mode "non-connecté" donc pas d'accès aux données de son territoire/OF.
![Image](https://user-images.githubusercontent.com/108516993/230051643-11d5c0c6-3f42-4ccf-b188-21f4fb0d8ea9.png)

**Comment by cathbaiona** [comment]
Bon, après avoir consulté le Slack du DSFR, l'option serait plutôt sur la modale, en enlevant le lien "Fermer" : 

![Image](https://user-images.githubusercontent.com/108516993/230108999-d0b68a78-3cbc-4846-884b-c17a898ea921.png)

**Comment by nadinelouchart** [comment]
ok - A la lecture de vos commentaire je vous propose de partir sur l'option 2 ;) - je valide et fais la carte
