### ISSUE TITLE
Evolution de la requête pour DREETS Bretagne

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2837]
Eléments à ajouter / ajuster dans le [CR de réunion](https://www.notion.so/mission-apprentissage/R-union-DGEFP-DREETS-Bretagne-01a9016f6ce74af281a93713d22b406a?pvs=4)

- [x] ajuster requête
- [ ] prévenir Nadine pour envoi de la requête + info sur fiab passée à 90% + permissions rétablies (cf tous les OF sont revenus sur leur vue)

**Comment by felixat13** [comment]
@nadinelouchart requêtes ajustées pur le dashboard Bretagne. J'ai ajouté des précisions dans un encart texte pour leur faciliter la lecture des colonnes de statut et historique de statut.
