### ISSUE TITLE
Fiabilisation / détection des doublons

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2852]
Plusieurs étapes : 

1. Normaliser nom+prénom (chaîne de caractère en **capitales**)
2. Détection Nom+ prénom + date de naissance + année scolaire ? (+ ID_ERP_APPRENANT à ne pas prendre) → CFD (RNCP?) 
    1. Clé 1 : NOM / PRENOM / DDN
    2. Clé 2 : NOM / PRENOM / DDN + ANNEE SCO
    3. Clé 3 : NOM / PRENOM / DDN + ANNEE SCO + CFD
3. Détection sur le reliquat 2. des doublons via l’année scolaire
4. Application des filtres de détection sur le reliquat 3.
    1. même organisme, sans relation ⇒ doublon détecté sur le même couple siret - uai fiable
    2. sur le reliquat a.  et si l’apprenant fait partie d’un organisme ayant des organismes en relation alors rechercher le doublon dans la même famille d’organismes (relations responsable/responsable-formateur/ formateur / lieu de formation) par couple siret-uai du responsable ou responsable formateur. 
    3. sur le reliquat suite aux filtres a et b ⇒ produire un signalement des jeunes entrés en formation dans 2 organismes différents.

Objectifs de repérage des : 

- Doublons au sein d’un même organisme 👉 https://github.com/mission-apprentissage/flux-retour-cfas/issues/2996
- Doublons au sein d’une famille d’organismes (envoyé par un responsable et aussi par un formateur par ex)
- Doublons entre différents organismes

**Comment by sbenfares** [comment]
Attendu dev/data : 

Fournir les listes à chaque étape avec doublon 1 et doublon 2 (etc.) pour comparer les infos.

- la liste présente doublon 1/doublon 2 avec nom/prénom/date de naissance/ OF/formation suivie
- côté admin : interface permettant de choisir lequel des doublons est à garder

Dans un 2ème temps, après analyse des listes, voir si pertinent d’appliquer un script  du type “ X% de caractères consécutifs de la chaine de caractère nomprénom  + date de naissance identiques” ⇒ détection d’un doublon

Définir quel doublon conserver et quel doublon rejeter

Produire les listes de doublons identifiés pour communication aux OF (correction à la source).
