### ISSUE TITLE
Mise à jour et validation de nouvelle CGU "tech dev"

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2860]
Suite à la mise en oeuvre du nouveaux parcours de connexion :

- [ ] Mettre en place la modale de validation des nouvelles CGU selon option 2 de la carte 
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2828 selon maquette 
 https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=10380%3A306855&t=TsBd2pmlsvH4mrJB-1

**Comment by rap2hpoutre** [comment]
@nadinelouchart C'est toujours à jour ? C'est à faire  (comme c'est dans todo)

**Comment by nadinelouchart** [comment]
je suppose que oui


Le 01/06/2023 à 14:54, Raphaël Huchet a écrit :
