### ISSUE TITLE
MAJ Documents RGPD Front

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2869]
Remplacer les éléments de Politique de confidentialité actuels par les éléments Protection des données (ces 2 pages ayant exactement la même structure)

- [x] Footer : retirer le lien "Données personnelles" (et donc l'écran vers lequel redirige le lien)
- [x] Footer : retirer le lien "Politique de confidentialité" (et donc l'écran vers lequel redirige le lien)
- [x] Footer : ajouter un lien "Protection des données", au clic, accès à un écran qui contient [ce texte](https://docs.google.com/document/d/1U8ljeuZZM7wcr_vzWBJNcC9EB2Tf3Fln/edit?usp=sharing&ouid=117555389785053708113&rtpof=true&sd=true)

![Image](https://user-images.githubusercontent.com/63646363/230614521-698ab29b-1000-4101-91f5-b8da4be73f3e.png)

**Comment by nadinelouchart** [comment]
ok vu
