### ISSUE TITLE
Export effectifs KO car effectifs sans organisme

### ISSUE THREAD

**Issue by totakoko** [mission-apprentissage/flux-retour-cfas#2910]
Environ 2000 effectifs en prod sont liés à des organismes qui n'existent plus. Or côté export des effectifs, on s'attend à avoir un organisme, donc 💥 .

Ils sont récupérables avec cette requête :
```js
db.getCollection("effectifs").aggregate([
 {
     
     $lookup:   {
          from: "organismes",
          localField: "organisme_id",
          foreignField: "_id",
          as: "organisme"
        }
 },
 {
     $match: {
         "organisme.0": {
             $exists: false
         }
     }
 }
])
```

@sbenfares Ca ressemble à un truc pour toi 😅

**Comment by sbenfares** [comment]
doublon de https://github.com/mission-apprentissage/flux-retour-cfas/issues/2849
