### ISSUE TITLE
modifier les vues indices du TdB au profit de la vue metabase

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2922]
Suite constat différence affichage des indices entre TdB (indice calendrier académique) et Metabase (indice calendrier calendaire) modifié TdB selon le modèle calendaire de données Metabase

Indices sur sur année de formation - année académique - Septembre 22 à Septembre 23 :
- [ ] Organismes de formation
- [ ] Apprentis
- [ ] Jeunes sans contrat
- [ ] Rupturants
- [ ] Abandons

+ Possible de filtrer sur période sur année calendaire - Année 2023 - Janvier à Décembre

**Comment by nadinelouchart** [comment]
@svengau  @totakoko @sbenfares si vous avez des questions revenez vers moi

**Comment by totakoko** [comment]
@nadinelouchart Concrètement :
- Est-ce que ça implique de changer les filtres disponibles côté UI, pour avoir par année académique ou année calendaire ?
- Sinon, est-ce qu'il faut juste changer la fonction qui calcule les années scolaires en fonction de la date pour passer de [n-1; n-1] et [n-1; n] à [n-1; n] et [n; n] ?

**Comment by totakoko** [comment]
Vu avec @nadinelouchart. Ce ticket concerne la 2e option, donc changer le mode de calcul des indicateurs.
