### ISSUE TITLE
Revue du parcours d'import / complétion d'effectifs / corrections d'effectifs "tech dev"

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#2930]
Suite à recette carte [#2537 ](https://github.com/mission-apprentissage/flux-retour-cfas/issues/2537)

- [ ] mise en prod technique selon maquette et parcours figma : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=9669%3A283886&t=KBWxEsBoOmkTGjTj-1

**Comment by svengau** [comment]
On va temporiser sur cette carte le temps de revoir le process d'upload pendant l'IRL.

2 cartes adjacentes sur lesquels on peut avancer:
- [] https://github.com/mission-apprentissage/flux-retour-cfas/issues/2951
- [] https://github.com/mission-apprentissage/flux-retour-cfas/issues/2953
