### ISSUE TITLE
Contrôle des rejets de données éventuellement liés à l'exigence date de mise à jour statut + heure

### ISSUE THREAD

**Issue by Anne-Camille** [mission-apprentissage/flux-retour-cfas#2968]
**Origine du besoin**

Données rejetées en entrée. Vu par Samir : possiblement lié au format "date maj statut+ heure"

**To do**

- [ ] Vérifier si des cas de rejets sont dus au format de date maj statut
- [ ] Si oui, rendre  l'entrée moins restrictive (suppression de l'heure ou acceptation du format date sans l'heure)

**Comment by Anne-Camille** [comment]
@sbenfares Je me suis permise de t'attribuer cette carte et de la mettre dans votre colonne BL tech pour que tu puisses éventuellement corriger la description pour la rendre plus compréhensible pour le dev qui prendra la vérification en charge.

**Comment by sbenfares** [comment]
Oui parfait merci !
