### ISSUE TITLE
Différence d'effectif entre metabase et le TDB

### ISSUE THREAD

**Issue by totakoko** [mission-apprentissage/flux-retour-cfas#2988]
On a une différence d'effectifs entre ceux remontés par metabase et ceux présents dans le TDB.
Les 2 requêtes sont différentes sachant que côté TDB, on filtre toujours avec une date, et pas côté metabase qui ne prend que la date courante.

Doit-on caler la requête metabase sur celle du TDB ? Ou adapter les 2 ?

A ce jour 5 mai 2023, total apprentis à date :
- metabase : 418 818
- tdb : 418 603

Metabase :
```js
[
    {
      $match: {
        annee_scolaire: {$in: ["2023-2023", "2022-2023"]},
        "apprenant.historique_statut.valeur_statut": 3,
      },
    },
    {
      $project: {
        historique_statut_apprenant: "$apprenant.historique_statut",
        organisme_id:1
      }
    },
    { $match: { historique_statut_apprenant: { $not: { $size: 0 } } } },
    {
      $addFields: {
        historique_statut_apprenant: {
          $sortArray: {input: "$historique_statut_apprenant",
              sortBy: { date_statut: 1, date_reception: 1 }}
        },
      },
    },
    {
      $addFields: {
        statut_apprenant_at_date: {
          $last: "$historique_statut_apprenant"
        },
      },
    },
    { $match: { "statut_apprenant_at_date.valeur_statut": 3 } },
    { $count: "Total Apprentis à Date"}
]
```

TDB :
```js
[
  {
    $match: {
      annee_scolaire: {
        $in: ["2023-2023", "2022-2023"],
      },
    },
  },
  {
    $match: {
      "apprenant.historique_statut.valeur_statut": 3,
    },
  },
  {
    $project: {
      "apprenant.historique_statut": {
        $filter: {
          input: "$apprenant.historique_statut",
          as: "result",
          cond: {
            $lte: ["$$result.date_statut", ISODate("2023-05-05T09:00:00.000Z")],
          },
        },
      },
    },
  },
  {
    $match: {
      "apprenant.historique_statut": {
        $not: {
          $size: 0,
        },
      },
    },
  },
  {
    $project: {
      "apprenant.historique_statut": {
        $sortArray: {
          input: "$apprenant.historique_statut",
          sortBy: {
            date_statut: 1,
            date_reception: 1,
          },
        },
      },
    },
  },
  {
    $addFields: {
      statut_apprenant_at_date: {
        $last: "$apprenant.historique_statut",
      },
    },
  },
  {
    $match: {
      "statut_apprenant_at_date.valeur_statut": 3,
    },
  },
  {
    $group: {
      _id: null,
      count: {
        $sum: 1,
      },
    },
  },
]
```

**Comment by Anne-Camille** [comment]
@totakoko @nadinelouchart on devrait avoir l'identique sur mb et sur la prod => on pourrait garder le principe de la prod (chiffres à la date de consultation par défaut ), et permettre de sélectionner par date/mois (prendre un arrêté au 28 ou 30 ou 31 de chaque mois pour l'affichage, comme en prod)/année sur metabase.

**Comment by totakoko** [comment]
Oui, je pense qu'il faudra faire un petit point la semaine prochaine avec @sbenfares et @felixat13 pour s'assurer qu'on requête bien le modèle de données.

**Comment by svengau** [comment]
Coté TDB, on doit garder la date, du coup il faudrait mettre a niveau Metabase. Le "hic" sur le temps réel, c qu'on peut recevoir plusieurs centaines de dossiers à la minute, donc on peut assez facilement avoir un delta entre les 2 en fonction du moment ou la page est accédé. Une solution: on ne prend jamais l'heure courante, mais arrondi à la derniere heure (ou demi-heure), des 2 cotés. 

Sinon, les requêtes ne sont pas exactement ISO, donc à harmoniser aussi.

**Comment by felixat13** [comment]
La différence vient effectivement d'un filtre sur la requête côté tdb, qui écarte les statuts qui ont une date d'application dans le futur. Ce qui doit provenir d'erreurs d'insertion de données, mais en tout cas il me parait logique de ne pas prendre en compte un jeune pour qui le statut apprenti a une date de début dans le futur si on veut le nombre d'apprentis à l'instant t.

Je suis d'avis qu'on garde donc la version du tdb avec le filtre `$lte: ["$$result.date_statut", ISODate("2023-05-05T09:00:00.000Z")]` avec la date du jour à la place de la date de l'exemple. Je peux modifier les requêtes MB pour qu'on soit iso. Qu'en pensez-vous @svengau @totakoko @sbenfares ?

**Comment by nadinelouchart** [comment]
je pense qu'il faut faire attention à cette donnée "statut apprenti a une date de début dans le futur" - suite à ce statut 2 questions se posent :
Est-ce que le jeune est en pré-apprentissage ? Ou est-il inscrit en CFA avec une date de démarrage de la formation dans le futur et un début de contrat en entreprise qui a démarré avant ? il faut choisir un ISO provisoire qui a mon sens devra evoluer dans le futur avec le nouveau schema de données
