### ISSUE TITLE
Bug affichage OF fermé alors que ouvert sur référentiel

### ISSUE THREAD

**Issue by nadinelouchart** [mission-apprentissage/flux-retour-cfas#3004]
corriger 

![Image](https://github.com/mission-apprentissage/flux-retour-cfas/assets/121936073/6adc967e-74f6-476c-b4a9-f085e683fcdf)

**Comment by svengau** [comment]
L'ERP n'envoie que l'UAI, alors que le SIRET est obligatoire depuis début janvier.
